### ISSUE TITLE
Bestätigungsmail sollte Antrag enthalten

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#101]
Ich hab grade einen Antrag gestellt und eine recht knappe Bestätigungsmail bekommen, daß der Antrag eingereicht wurde und jetzt geprüft wird. Das hinterläßt ein etwas unsicheres Gefühl, ob der Antrag richtig angekommen ist, u.a. weil man ja dann auch nichts in der Hand hat, um es im Zweifel nachzuweisen. Die Mail sollte den gestellten Antrag (einschließlich Unterstützer*innen) enthalten.

**Comment by CatoTH** [comment]
Die Mail enthält aber schon einen Link auf den Antrag, oder?
Ja wäre natürlich gut, den Antrag mit beizufügen. Muss man halt nur schauen, ob man dann auf HTML-Mails umstellt um den Antrag auch richtig darzustellen, oder ob man sich mit einer Zu-Plaintext-Konvertier-Variante begnügt (die aber ohnehin nötig ist, weil Nur-HTML-E-Mails eher ungünstig sind).

**Comment by CatoTH** [comment]
DBJR-Feedback:
> Mails an Antragsteller_innen sollten Änderungsantrags-Inhalt mitschicken, um später darauf zurückgreifen zu können (vor allem, weil ÄA bei aktualisierten Fassungen nicht mehr ohne Weiteres zugreifbar sind).
