### ISSUE TITLE
Einige Probleme im Installationsmodus

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#104]
Im Installationsmodus treten folgende Probleme auf:
1. Beim Abschicken des Formulars kommt man auf eine weiße Seite, auf der nur "Setting Admin user?Setting Admin user?Setting Admin user?" steht. (Das wird in models/forms/AntragsgruenInitForm.php ausgegeben.)
2. Die "Voreinstellung: BDK" wird nicht gespeichert; beim erneuten Aufrufen erscheint wieder "Voreinstellung: Anträge" (obwohl andere Einstellungen, z.B. Datenbankname, gespeichert werden).
3. An die URL wird bei jedem erneuten Speichern der Seite ein weiteres Mal "/web" rangehängt.
4. In der URL, die beim Beenden des Installationsmodus ausgegeben wird, fehlt ein Schrägstrich (bei mir: "http://bdk.devconsultation/index", sollte "http://bdk.dev/consultation/index" heißen).

**Comment by CatoTH** [comment]
Kannst du mir vielleicht noch ein paar weitere Informationen zu deiner Umgebung schicken? Weil abgesehen von 2) konnte ich die Fehler jetzt nicht reproduzieren...
Also Webserver, Pfad, URL usw.
