### ISSUE TITLE
Drücken von <shift> oder <alt> löscht Auswahl in Änderungsantragsfeld 

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#116]
Wenn man im Textfeld für Änderungsanträge Text auswählt und dann `<shift>` oder `<alt>` (aber nicht `<fn>`, `<ctrl>` oder `<cmd>`) drückt, wird der Text gelöscht. Das sollte nur passieren, wenn man Text eingibt.

**Comment by CatoTH** [comment]
Ich kann das gerade nicht reproduzieren. Passiert es z.B. hier auf https://bdk.antragsgruen.de/39/motion/118/amendment/create , wenn ich etwas markiere und dann Shift oder alt drücke? Oder hat sich der Fehler durch den letzten Update vom Editor von selbst erübrigt?

**Comment by joriki** [comment]
Ich kann es auch nicht mehr reproduzieren -- ja, vermutlich hat es sich dann durch das Update erübrigt. Ich schließe das Issue und öffne es wieder, wenn das Problem noch mal auftritt.
