### ISSUE TITLE
Dringlichkeitsbegründung für Dringlichkeitsanträge

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#121]
Das eilt nicht; fiel mir nur grade auf: Im Moment deutet nichts außer dem kleinen "keine Einfahrt"-Icon beim Einreichen darauf hin, daß man einen Antrag nach Antragsschluß einreicht. Es wäre gut, in diesem Fall ein zusätzliches Eingabefeld für eine Dringlichkeitsbegründung zu haben, mit einer kurzen Erklärung drüber, dass die Antragsfrist für diesen Antrag abgelaufen ist und vielleicht mit dem Satz aus der Geschäftsordnung, wann Dringlichkeit gegeben ist. (Der genaue Text wäre noch mit der BGS zu koordinieren.)

**Comment by CatoTH** [comment]
Es ist ein handfester Bug, dass es aktuell überhaupt noch möglich ist, Anträge zu stellen (#131).

Das mit den Dringlichkeitsanträgen ließe sich anders lösen: über einen zusätzlichen Antragstyp, der ein zusätzliches Feld und einen anderen Antragsschluss hat. Das Anlegen von Antragstypen übers Webinterface bau ich morgen oder übermorgen noch ein (#100).
