### ISSUE TITLE
pdf läste sich nicht erzeugen

### ISSUE THREAD

**Issue by gerhardlippe** [CatoTH/antragsgruen#129]
Beim Antrag GW-KS-01-322 kann ich keine pdf erzeugen - es kommt die Meldung

"Ein Fehler trat auf: exception 'yii\base\ErrorException' with message
'DOMDocument::loadHTML(): Unexpected end tag : em in Entity, line: 3' in
/var/www/antragsgruen/components/latex/Exporter.php:175 Stack trace: #0
[internal function]: yii\base\ErrorHandler->handleError(2,
'DOMDocument::lo...', '/var/www/antrag...', 175, Array) #1
/var/www/antragsgruen/components/latex/Exporter.php(175):
DOMDocument->loadHTML('<html><head>\n<m...') #2
/var/www/antragsgruen/models/sectionTypes/TextSimple.php(467):
app\components\latex\Exporter::encodeHTMLString('<h4 class="line...') #3
/var/www/antragsgruen/views/amendment/LayoutHelper.php(66):
app\models\sectionTypes\TextSimple->getAmendmentTeX() #4
/var/www/antragsgruen/views/amendment/pdf_tex.php(27):
app\views\amendment\LayoutHelper::renderTeX(Object(app\models\db\Amendment))
#5 /var/www/antragsgruen/vendor/yiisoft/yii2/base/View.php(325):
require('/var/www/antrag...') #6
/var/www/antragsgruen/vendor/yiisoft/yii2/base/View.php(247):
yii\base\View->renderPhpFile('/var/www/antrag...', Array) #7
/var/www/antragsgruen/vendor/yiisoft/yii2/base/View.php(149):
yii\base\View->renderFile('/var/www/antrag...', Array,
Object(app\controllers\AmendmentController)) #8
/var/www/antragsgruen/vendor/yiisoft/yii2/base/Controller.php(402):
yii\base\View->render('pdf_tex', Array,
Object(app\controllers\AmendmentController)) #9
/var/www/antragsgruen/controllers/AmendmentController.php(40):
yii\base\Controller->renderPartial('pdf_tex', Array) #10 [internal
function]: app\controllers\AmendmentController->actionPdf('125', '198')
#11 /var/www/antragsgruen/vendor/yiisoft/yii2/base/InlineAction.php(55):
call_user_func_array(Array, Array) #12
/var/www/antragsgruen/vendor/yiisoft/yii2/base/Controller.php(151):
yii\base\InlineAction->runWithParams(Array) #13
/var/www/antragsgruen/vendor/yiisoft/yii2/base/Module.php(455):
yii\base\Controller->runAction('pdf', Array) #14
/var/www/antragsgruen/vendor/yiisoft/yii2/web/Application.php(84):
yii\base\Module->runAction('amendment/pdf', Array) #15
/var/www/antragsgruen/vendor/yiisoft/yii2/base/Application.php(375):
yii\web\Application->handleRequest(Object(yii\web\Request)) #16
/var/www/antragsgruen/web/index.php(29): yii\base\Application->run() #17
{main}"

**Comment by CatoTH** [comment]
Müsste inzwischen behoben sein (https://github.com/CatoTH/antragsgruen/commit/8014633edaadd7b3d7bafb0897952202a99cb34c) . Ich schau mal, ob man noch was gegen die "zerklüftete" Änderungsansicht machen kann.
