### ISSUE TITLE
Einzelne unveränderte Buchstaben erscheinen im Diff verändert

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#132]
86e6a4020bbaded1fba355bfd3e1c25d2f9cb789 hat einen Fehler eingeführt; Beispiel: https://bdk.antragsgruen.de/39/admin/amendment/update/201. Hier wird eigentlich nur gelöscht; stattdessen erscheint jetzt das 'e' hinter der Löschung als gelöscht und eingefügt. Das Problem hat mit diesen Zeilen in `Diff::getUnchangedPrefixPostfix` zu tun:

>             if ($postfixLen > 40 && mb_strpos($postfix, '. ') < 40) {
>                $postfix = mb_substr($postfix, mb_strpos($postfix, '. ') + 1);

Wenn der Suchstring '. ' nicht vorkommt, gibt mb_strpos FALSE zurück, und FALSE + 1 = 1. Dieses Problem bestand schon vor der Änderung aber hat sich nicht ausgewirkt, weil die Abfragen in `Diff::computeDiff` anders waren.

**Comment by CatoTH** [comment]
Ich hab das Problem jetzt mal anders gelöst. Die oben genannte Zeile schaut aber in der Tat auch seltsam aus, deswegen lass ich den Issue jetzt mal noch offen.
Wahrscheinlich wären extra Testfälle für diese Funktion sinnvoll...
