### ISSUE TITLE
Editor für Änderungsanträge markiert anfängliche Änderungen nicht [Firefox on Mac]

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#138]
Wenn ich einen neuen Änderungsantrag stelle (z.B. https://bdk.antragsgruen.de/39/motion/125/amendment/create), gibt es ein Zeitfenster von einigen Sekunden, in dem ich Änderungen (sowohl Einfügung als auch Streichung) im Text vornehmen kann, ohne dass sie als solche markiert werden. Der genaue Ablauf ist: Ein paar Sekunden lang erscheint schon der Text, aber ich kann noch nichts ändern; die Toolbar über dem Editor wird noch nicht angezeigt; wenn ich Text auswähle und <Backspace> drücke, geht der Browser zur Seite davor zurückt. Dann erscheint die Toolbar, und ein paar Sekunden lang kann ich Änderungen vornehmen, ohne dass sie als solche markiert werden. Dann erst fängt die Markierung an; die vorher geänderten Stellen werden auch im Nachhinein nicht markiert.

Das tritt in Firefox 41.0.2 auf Mac OS 10.10.5 auf, in Safari 9.0.1 (10601.2.7.2) nicht.

**Comment by CatoTH** [comment]
Ich weiß nicht, ob das Problem immer noch besteht... aber falls ja, befürchte ich, dass ich das auch nicht mit realistischem Aufwand beheben kann. (Und es haben sich in den Jahren auch sonst nicht mehr wirklich Leute darüber beschwert)
