### ISSUE TITLE
Nach Admin-Bearbeitung eines Änderungsantrags wird zunächst das alte Diff angezeigt

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#140]
Wenn ich (in Firefox auf Mac) einen Änderungsantrag als Admin bearbeite, kriege ich zunächst trotzdem das alte Diff angezeigt. Wenn ich neu lade, wird dann das richtige angezeigt. Eigentlich wird in `controllers\admin\AmendmentController::actionUpdate` vor dem Rendern der neuen Seite `$amendment->motion->flushCacheWithChildren()` aufgerufen, und dass es später richtig angezeigt wird, scheint ja auch zu zeigen, dass das funktioniert. Ich vermute, dass es an unsynchronisiertem Datenbankzugriff liegt, d.h. das Rendern sieht noch eine Version, in der der cache flush noch nicht ausgeführt wurde? Kann man die Zugriffe explizit synchronisieren?

Dasselbe Problem könnte theoretisch auch eigenständige Anträge betreffen; da weiß ich nur nicht, wie es sich bemerkbar machen würde, wenn ein veralteter Cache verwendet wird.

**Comment by CatoTH** [comment]
Das wird durch https://github.com/CatoTH/antragsgruen/pull/139 ja behoben, oder?

**Comment by joriki** [comment]
Sorry, ich hatte vor das zu verlinken und dazuzuschreiben, dass es ein separates Problem ist, aber hab es vergessen. Nein, das wird nicht dadurch behoben. Bei #139 fehlte das flushen im Code; in diesem Fall wird eigentlich geflusht, aber irgendwie wirkt es sich nicht rechtzeitig aus. Warum es sich bei #139 rechtzeitig auswirkt, weiß ich nicht; wenn ich raten müßte, würde ich sagen, weil ich dort flush vor save gesetzt hab und hier das flush fast das letzte vor dem Rendern ist -- vielleicht erzwingt save eine Synchronisation oder so.
