### ISSUE TITLE
Diff-Darstellung von Leerzeichen und Zeilenumbrüchen verbessern

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#141]
Die Darstellung von Leerzeichen und Zeilenumbrüchen ist manchmal nicht optimal. Beispiel: https://bdk.antragsgruen.de/39/motion/144/amendment/281. Hier wurde ein Leerzeichen durch einen Zeilenumbruch ersetzt -- das Einfügen des Zeilenumbruchs ist nicht explizit dargestellt, dafür aber die Streichung des Leerzeichens, die eine triviale Folge des Einfügens des Zeilenumbruchs ist und eigentlich nicht explizit dargestellt werden müßte, wenn das Einfügen erkennbar wäre.

**Comment by joriki** [comment]
Weiteres Beispiel: https://bdk.antragsgruen.de/39/admin/amendment/update/284

**Comment by CatoTH** [comment]
Und https://bdk.antragsgruen.de/39/motion/125/amendment/324

**Comment by joriki** [comment]
Dieser letzte scheint inzwischen gelöscht worden zu sein -- ich kriege die Index-Seite, wenn ich ihn aufrufe.

**Comment by CatoTH** [comment]
Ja aber der Text ist noch in der Datenbank, so konnte ich nachschauen ^^
