### ISSUE TITLE
Durchstreichen führt zu verwirrendem Diff

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#142]
Das Diff für https://bdk.antragsgruen.de/39/motion/144/amendment/297 ist sehr verwirrend; das wird anscheinend dadurch verursacht, dass der zu streichende Teil durchgestrichen anstatt gelöscht wurde (was aber im Diff nicht zu erkennen ist).

**Comment by CatoTH** [comment]
Erkennen könnte man es evtl daran, ob es rot oder grün ist, oder ging das auch nicht? Inzwischen scheint es ja (redaktionell) behoben zu sein?
Mir fällt halt kaum eine Möglichkeit ein, das zu beheben, jenseits von "Durchstreichen wieder verbieten", ggf. auch nur in Änderungsanträgen?

**Comment by joriki** [comment]
Nein, es war weder rot, noch grün, weil sie es nicht gelöscht, nur durchgestrichen hatten. Es stand:

In Zeile XXX einfügen: ... Text ...

und der Text war schwarz; dadurch war der Eindruck, daß dieser Text eingefügt werden sollte; gemeint war wohl, daß ein (öffnender und schließender) `<strike>`-Tag eingefügt werden sollte, den man aber nicht sehen konnte.

**Comment by joriki** [comment]
Ein weiteres Beispiel hierfür: https://bdk.antragsgruen.de/39/motion/144/amendment/219

**Comment by joriki** [comment]
Weiteres Beispiel, mit teilweiser Durchstreichung: https://bdk.antragsgruen.de/39/motion/144/amendment/219

**Comment by patrickhanft** [comment]
Auch wenn es aus einer bestimmten Perspektive nicht pragmatisch erscheint und ich mich damit ggf. unbeliebt mache, aber ehrlich gesagt finde ich, dass genau aus diesem Grund solche Formatierungen wie beispielsweise „durchstreichen“ vom Antragstool nicht unterstützt werden sollten. 

Ich mag mich täuschen, aber auch in Gesetzestexten erscheinen mir solche Formatierungsmöglichkeiten nicht üblich.

**Comment by CatoTH** [comment]
Es gibt das Durchstreichen halt wegen https://github.com/CatoTH/antragsgruen/issues/42 , also insb. um Satzungsänderungsanträge stellen zu können, ohne dazu zwei Schritte gehen zu müssen (erst mal die aktuelle Satzung als "Antrag" anlegen um dann anschließend den Änderungsantrag stellen zu können).
Deshalb oben mein Kompromissvorschlag, Durchstreichen nur bei normalen Anträgen, nicht aber bei Änderungsanträgen zuzulassen. (Was aber Probleme machen würde, falls man einen Änderungsantrag zu einem Satzungsänderungsantrag stellen will - aber das führt wieder zu der alten theoretischen Diskussion, ob überhaupt Änderungsanträge für Änderungsanträge möglich sein sollten... was IMHO immer noch eine eher hypothetische Frage ist).

**Comment by joriki** [comment]
Bei Änderungsanträgen kein Durchstreichen zu erlauben, wäre OK; ich kann mir schwer eine Situation vorstellen, in der man tatsächlich durchgestrichenen Text im fertigen Beschluss haben wollen würde. Das löst allerdings nicht das Problem von Unterstreichen und Kursivstellen, weil das schon möglich sein sollte. (Ein Beschluss ist kein Gesetzestext; es geht nicht um eine möglichst genaue und eindeutige Auslegung sondern u.a. um politische Botschaften, die man hervorheben wollen könnte.) Wenn das weiterhin erlaubt ist, brauchen wir glaube ich zwei Dinge: Erstens eine gute Anzeige dafür, wenn die Formatierung geändert wurde (das ist im Moment gar nicht zu erkennen), und zweitens einen prominenten Hinweis (in der Handreichung zur Antragseinreichung und/oder in Antragsgrün selbst), daß Änderungen automatisch markiert werden und einfach vorgenommen und nicht markiert werden sollten.

**Comment by CatoTH** [comment]
DBJR-Feedback:
> Änderungsantrag einreichen: Hier darf der Editor keine Durchstreich-Formatierungsmöglichkeit anbieten, weil sie missverständlich zur Funktion „löschen“ ist.

**Comment by CatoTH** [comment]
Durch https://github.com/CatoTH/antragsgruen/commit/192b56013fd362bb24c513012a6c7b80d5c64406 wird in v3.1 dann Durchgestrichen bei Änderungsanträgen verhindert.
