### ISSUE TITLE
Einige Verbesserungen in der ODT-Ausgabe

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#143]
In den ODTs wird nur eine Antragsteller*in angezeigt, aber davor steht "AntragstellerInnen" -- es sollten entweder alle angezeigt werden oder "AntragstellerIn" im Singular stehen. (Wenn wie erwartet der S-01 zur geschlechtergerechten Sprache angenommen wird, sollten wir übrigen in Zukunft auch hier den Gender-Star verwenden.)

Die Überschrift "Antrag: Kürzel: ..." sieht etwas komisch aus; das "Antrag" steht glaube ich in anderen Darstellungen nicht und ist eigentlich überflüssig?

Bei Änderungsanträgen fehlen in "In Zeile X einfügen" u.ä. die Leerzeichen.

**Comment by CatoTH** [comment]
Die ersten beiden Punkte hab ich jetzt umgesetzt. Aber was genau meinst du mit Leerzeichen?

**Comment by joriki** [comment]
Ich sehe jetzt, dass da im Text doch Leerzeichen sind und sie bei mir nur sehr schlecht dargestellt werden (OpenOffice 4.1.1 auf Mac OS 10.10.5). Hier ist ein Screenshot:

<img width="554" alt="bildschirmfoto 2015-10-30 um 11 01 50" src="https://cloud.githubusercontent.com/assets/1418717/10842908/b42b169a-7ef5-11e5-9aa1-6cdd9a3cfde2.png">

**Comment by CatoTH** [comment]
Liegt das an der Schriftart? Oder was muss man ändern, damit das passt?

**Comment by CatoTH** [comment]
Irgendwelche Erkenntnisse dazu? Ansonsten würde ich den Issue dann schließen.
