### ISSUE TITLE
unnötige Streichung und Einfügung

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#145]
Hier ist in Zeile 55/56 "einzuschlagen." gestrichen und eingefügt, obwohl sich nichts geändert hat:

https://bdk.antragsgruen.de/39/motion/125/amendment/324

Es ist nur ein Entwurf; er wird sich vielleicht bald ändern; aber ich weiß nicht, wie ich ihn fixieren könnte.

**Comment by CatoTH** [comment]
Duplikat von https://github.com/CatoTH/antragsgruen/issues/141
