### ISSUE TITLE
Falsche Inline-Diff-Darstellung in bullet points

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#147]
Bei diesen ÄAs zu bullet points wird in der Inline-Diff-Darstellung im Antrag der gesamte Text in den bullet points als eingefügt dargestellt (soweit er nicht gestrichen wurde), obwohl Teile davon eigentlich schon vorhanden waren (und in der separaten Diff-Darstellung des ÄAs auch richtig entsprechend dargestellt werden):

GW-KS-02-121: https://bdk.antragsgruen.de/39/motion/133/amendment/323
GW-KS-02-149: https://bdk.antragsgruen.de/39/motion/133/amendment/171

**Comment by CatoTH** [comment]
In GW-KS-02-149 seh ich das Problem auf Anhieb nicht. Bei GW-KS-02-121 hab ich gefunden, woran es liegt, allerdings ist die Fehlerbehebung etwas komplizierter. Das Problem ist hier, dass hier ein Absatz innerhalb eines Listenpunkts aufgemacht wird, anschließend geht es weiter (der Punkt, der im Änderungsantrag doppelt enthalten ist). Ich würde jetzt einfach erst mal den Doppelten Punkt entfernen, dann sollte es wieder richtig aussehen. Den eigentlichen Fehler würde ich dann bei der nächsten Version beheben - den Teil des Codes muss ich wegen #120 ohnehin nocheinmal angehen.

**Comment by joriki** [comment]
Für GW-KS-02-149, Screenshots der falschen Inline-Darstellung:

![gw-ks-02-149-inline](https://cloud.githubusercontent.com/assets/1418717/10998027/49224a6a-8492-11e5-9d73-885ab32a2949.png)

und der richtigen separaten Darstellung:

<img width="793" alt="gw-ks-02-149-separat" src="https://cloud.githubusercontent.com/assets/1418717/10998029/4c1a3fca-8492-11e5-92cf-4a87ff80bfeb.png">
