### ISSUE TITLE
Anträge vor dem Stellen entwerfen und Unterstützung sammeln

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#176]
Langfristig sollte es möglich sein, einen Antrag in antragsgrün zu entwerfen, einen Link an potenzielle Unterstützer*innen zu schicken und dann erst Unterstützer*innen einzutragen und den Antrag formal zu stellen. Dann bräuchte man nicht mehr den Antrag erst einmal für die Unterstützer*innen ausformulieren und verschicken und dann noch mal getrennt in antragsgrün eingeben; und die Unterstützer*innen würden ihn gleich in genau der Form sehen, in der er nachher als Diff erscheint.

**Comment by CatoTH** [comment]
Das sollte in v3.2 hoffentlich durch https://github.com/CatoTH/antragsgruen/commit/dca00cd8b0d326bbc36398070c065fd89e8a7c18 weit gehend abgedeckt werden.
