### ISSUE TITLE
Anträge in antragsgrün unterstützen

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#177]
Es sollte möglich sein (wenn man als Mitglied eingeloggt ist), Unterstützung für einen Antrag zu signalisieren -- im Nachhinein als Meinungsäußerung und/oder im Zusammenhang mit #176, wenn ein Entwurf noch nicht eingereicht ist, als formale Unterstützung zur Einreichung.

**Comment by CatoTH** [comment]
Das sollte in v3.2 hoffentlich durch https://github.com/CatoTH/antragsgruen/commit/dca00cd8b0d326bbc36398070c065fd89e8a7c18 weit gehend abgedeckt werden.
