### ISSUE TITLE
Zend framework missing in composer.json

### ISSUE THREAD

**Issue by andi98** [CatoTH/antragsgruen#179]
Antragsgrün 3 seems to need some packages from the zendframework but they are not mentioned in composer.json, so a simple `./composer.phar install` would end in PHP-errors like `PHP Fatal error:  Class 'Zend\\Mail\\Message' not found`

**Comment by CatoTH** [comment]
It should be installed as a dependency of slm/mail - https://github.com/juriansluiman/SlmMail/blob/master/composer.json lists "zendframework/zend-mail": "~2.0" as a dependency.
Is it not getting installed on your server?

**Comment by andi98** [comment]
Okay, sorry, my mistake. I've reinstalled antragsgrün with composer and zend-mail were installed too!
