### ISSUE TITLE
Antragsart und Antragstitel als einheitlichen Link verlinken

### ISSUE THREAD

**Issue by peduso** [CatoTH/antragsgruen#187]
Die Links auf der Startseite setzen sich aus zwei Teilen zusammen

Antragsart Antragstitel (dahinter noch der Link zum PDF)

Der Mouseover wird zwischen Antragsart und Antragstitel unterbrochen und das macht den Eindruck es handle sich um unterschiedliche Ziele. In Mozilla wird unten das Ziel angezeit und wenn man genau hin schaut ist sichtbar, dass sich um ein und das selbe Ziel handelt. Daher fänd ich es cool, wenn der Mousover nicht unterbrochen würde.

**Comment by CatoTH** [comment]
Hallo,

ich hab das eben umgesetzt (https://github.com/CatoTH/antragsgruen/commit/80f559b32c483981c668a5ee397767bed611c440). Auf antragsgruen.de wird es dann eingespielt, sobald die nächste größere Version fertig ist (das dürfte noch 1-2 Wochen dauern).

**Comment by CatoTH** [comment]
@peduso Die neue Version mit der Änderung ist jetzt online.

**Comment by peduso** [comment]
Top, vielen Dank!
