### ISSUE TITLE
Hidden ÄA

### ISSUE THREAD

**Issue by macwinnie** [CatoTH/antragsgruen#195]
Zur Vorbereitung von Veranstaltungen ist es ab und an sinnvoll, gewisse "Kompromisse" als Änderungsanträge bereits vorzubereiten. Diese sollen natürlich nicht von vornherein für alle sichtbar sein, sondern nur bei Bedarf eingespielt werden.

**Comment by CatoTH** [comment]
Es gibt seit kurzem einen neuen Status "Entwurf (Admin)", der nicht auf in der regulären (Änderungs-)Antragsübersicht auftaucht. Solche Änderungsanträge können dann später vom Admin auf sichtbar ("Eingereicht") gestellt werden. Ist das ungefähr das, vielleicht ist das ja ungefähr das, was ihr euch vorgestellt habt?

**Comment by CatoTH** [comment]
Die Verfahrensvorschläge, die mit 3.8 eingeführt wurden, sollten das soweit eigentlich abdecken. Man muss dann nur als Verfahrensvorschlag für einen ÄA auf "Modifizierte Übernahme" stellen, dann kann man die modifizierte Version parallel zum regulären ÄA schreiben - und später dann ggf. sichtbar machen.
