### ISSUE TITLE
Zeilenangaben in Diffs sollten Änderung, nicht Kontext widerspiegeln

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#204]
Z.B. hier: https://bdk.antragsgruen.de/40/Ja_zu_Europa_Mut_zur_Veraenderung_-_Europas_Zukunft_gemeinsam_gestalte-18553/2592
Die Einfügung ist in Z. 302, der Antrag hat auch entsprechend die Nummer E-01-302 gekriegt, aber im Diff steht "Von Zeile 301 bis 302 einfügen:". Der dargestellte Kontext fängt in Zeile 301 an, aber die Zeilenangabe sollte die Änderung beschreiben, nicht den Kontext, also "In Zeile 302 einfügen:".

**Comment by CatoTH** [comment]
Ist inzwischen behoben.
