### ISSUE TITLE
Mehrere Absätze als Ganzes ersetzen

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#207]
Frederik schriebt zu diesem Änderungsantrag von ihm: https://bdk.antragsgruen.de/40/EU-Beitrittsgespraeche_mit_der_Tuerkei_nutzen__Tuer_fuer_Demokratie_Mens-43690/2914 (E-02-001 auf der BDK 2016 in Münster), daß er lieber die ersten beiden Absätze als Ganzes durch die vier neuen Absätze ersetzt sehen würde, nicht wie aktuell im Diff den ersten durch den ersten und den zweiten durch den zweiten. Ich weiß nicht, ob wir automatisch erkennen können, wann das sinnvoll wäre -- z.B. wenn die Ähnlichkeit der Absätze unter einer bestimmten Schwelle ist. Sonst könnten wir die Benutzer*in markieren lassen, was wodurch ersetzt wird, aber das wäre eine ziemlich grundsätzliche Änderung.

**Comment by CatoTH** [comment]
Das wird durch https://github.com/CatoTH/antragsgruen/commit/519d42c658d01bcf5aeef9bd7d37a5072225f781 und die folgenden Commits behoben. Im aktuellen Stand des v3.7-Branches schaut der Antrag dann folgendermaßen aus:

![bildschirmfoto 2017-04-12 um 11 03 32](https://cloud.githubusercontent.com/assets/533440/24950008/d107fb0e-1f6f-11e7-85b2-658573e4b94a.png)
