### ISSUE TITLE
Nur 18 Unterstützer*innen angebbar

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#209]
Georg Kössler hat zur BDK 2016 in Münster einen Antrag per Mail eingereicht, weil in antragsgrün nur 18 Unterstützer*innen angebbar gewesen seien. Ich versuche mit ihm zu klären, was da passiert sein könnte (er war im Urlaub, also vielleicht phone-bedingt); erst mal kein Handlungsbedarf; ich schreibe es nur hier rein, damit wir es nicht vergessen.

**Comment by joriki** [comment]
Ich hab inzwischen mit Georg geredet -- er war auf dem iPad; ich hab ihn gebeten, seinen user agent zu schicken -- das Ergebnis:

{ "ua": "Mozilla/5.0 (iPad; CPU OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A456 Safari/602.1", "browser": { "name": "Mobile Safari", "version": "10.0", "major": "10" }, "engine": { "version": "602.1.50", "name": "WebKit" }, "os": { "name": "iOS", "version": "10.0.2" }, "device": { "model": "iPad", "vendor": "Apple", "type": "tablet" }, "cpu": {} }

**Comment by CatoTH** [comment]
Ich konnte den Fehler leider auf mehreren iOS-Geräten nich reproduzieren. Ich vermute mal, du auch nicht, oder?
