### ISSUE TITLE
Bei Zurück-Button gehen Änderungen verloren

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#210]
Moritz Heuberger hat zur BDK 2016 in Münster aus Versehen einen leeren Antrag eingereicht, weil er auf dem Phone nach links geswiped hat und damit im Browser eine Seite zurückgegangen ist; dabei sind offenbar die vorgenommenen Änderungen verlorengegangen. Wenn möglich sollten sie erhalten bleiben.

**Comment by CatoTH** [comment]
Es gibt inzwischen (bei der neuen 3.7er-Version) eine Sicherheitsabfrage, ob man die Seite verlassen will, wenn es ungespeicherte Änderungen gibt. Zuvor müsste es aber auch schon ungespeicherte Entwürfe gegeben haben - aber da kanns natürlich sein, dass das auf dem speziellen Phone nicht funktioniert hatte.
