### ISSUE TITLE
Probleme mit Korrigieren-Button

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#211]
Gerhard berichtet, daß manchmal wenn er einen Änderungsantrag anlegt und auf "Korrigieren" klickt, danach falsche Änderungen angezeigt werden. Ich konnte das nicht auf Anhieb reproduzieren; vielleicht kann Gerhard genauer sagen, wann das Problem auftritt.

**Comment by CatoTH** [comment]
Falls es wieder auftritt, einfach nochmal melden. Aber da ich jetzt nichts mehr gehört habe, gehe ich davon aus, dass der Fehler nicht mehr auftaucht.
