### ISSUE TITLE
Admin-Bearbeitung von Unterstützer*innen funktioniert in Firefox nicht

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#212]
Ich kann in Firefox 49.0.2 ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:49.0) Gecko/20100101 Firefox/49.0") als Admin nicht die Ünterstützer*innen bearbeiten. Ich kann zwar neue Felder hinzufügen, aber weder welche löschen, noch die Inhalte bestehender Felder bearbeiten. In Safari funktioniert das alles.

**Comment by CatoTH** [comment]
@joriki Kannst du einmal schauen, ob es bei euch jetzt wieder funktioniert? Mir scheint das ein Bug im Firefox zu sein, für den ich mal einen Work-Around eingebaut habe...

**Comment by joriki** [comment]
@CatoTH Ja, danke, funktioniert!
