### ISSUE TITLE
Herunterladen aller pdf-Dateien

### ISSUE THREAD

**Issue by gerhardlippe** [CatoTH/antragsgruen#217]
Sammeldatei, läst sich nicht laden, egal mit welchem Gerät und zu welcher Uhrzeit

**Comment by macwinnie** [comment]
Vlt. ist die gesamte Dateigröße größer, als der PHP maximal zugestandene Arbeitsspeicher? Dann ist die Server-Config anzupassen.

**Comment by thoessl** [comment]
Ich vermute eher, dass die Berechnung zu lange dauert und in einen Timeout läuft. Ich schau mal, dass ich noch ein besseres Caching einbaue, damit das PDF nicht jedes Mal komplett neu berechnet werden muss.

**Comment by CatoTH** [comment]
Ich hab nun zusätzliches Caching eingebaut, das das ganze deutlich verbessern sollte.
