### ISSUE TITLE
Schriften in odt-Dateien müssen mit pdf identisch sein

### ISSUE THREAD

**Issue by gerhardlippe** [CatoTH/antragsgruen#218]
in den pdf-Dateien haben wir als Schrift pt-sans in den odt-Dateien hat der Fließtext die Schrift Courier 10 Punkt. Dadurch laufen die Zeilen "aus dem Ruder". Wir brauchen in den odt-Dateien ebenfalls pt-sans, damit die Zeilen identisch mit den pdf-Dateien sind.

**Comment by CatoTH** [comment]
Ok, ist jetzt behoben - war nur eine Komplikation mit dem neuen Design.
