### ISSUE TITLE
Versionschaos bei eingebundenen Paketen (composer)

### ISSUE THREAD

**Issue by macwinnie** [CatoTH/antragsgruen#223]
Hi @CatoTH,

bei mir haut mal wieder einiges nicht hin beim Update ... und ich hab die Befürchtung, dass es an "zu neuen" Abhängigkeiten liegen kann.
Es fehlt die `composer.lock`-Datei, welche dafür sorgen würde, dass auf anderen Systemen exakt die selben Abhängigkeiten wie in deinem System installiert werden. Ein `composer update` sollte wirklich nur dann vorgenommen werden, wenn es notwendig ist – bestenfalls von dir bei Veröffentlichung eines neuen Release.

Bitte füge die `composer.lock` dem Repo hinzu.

Danke und viele Grüße =)
Martin

**Comment by CatoTH** [comment]
Ok, ich hab die Datei mit ins Repository aufgenommen. Wobei ich doch vorwarnen muss, dass ich vergleichsweise häufig die Abhängigkeiten aktualisiere, da ich doch gerne die aktuellsten Patch-Levels der verwendeten Bibliotheken am Laufen habe.
