### ISSUE TITLE
Fehler "Keine Daten angegeben (Feld: Antragstext)" bei nicht getippten Änderungen

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#224]
Wenn Änderungen an einem Antrag gepastet oder per JavaScript vorgenommen werden, erscheint beim Klicken auf "Weiter" statt der Bestätigungsseite die Fehlermeldung "Keine Daten angegeben (Feld: Antragstext)". Das scheint daran zu liegen, dass in diesem Fall die Textarea "consolidated" leer bleibt.

Um das Problem zu reproduzieren: Zu einem Antrag auf https://bdk-test2.antragsgruen.de gehen, "Änderungsantrag stellen", beliebigen Text kopieren und in den Antragstext pasten. Telefonnummer ausfüllen und auf "Weiter" klicken.

Der Fehler tritt nicht auf, wenn man vor "Weiter" noch einmal in das Antragstext-Feld klickt; offenbar wird dann "consolidated" eingefüllt. Er tritt auch nicht auf, wenn man die Änderung tippt, anstatt sie zu pasten. Er tritt aber auf, wenn man von JavaScript aus den Inhalt des Antragstext-div ändert. Es geht also offenbar darum, welche Events eine Aktualisierung von "consolidated" auslösen.

**Comment by CatoTH** [comment]
Da scheinen sich leider zwei CKEditor-Plugins in die Quere gekommen zu sein, Undo und TrackChanges (http://dev.ckeditor.com/ticket/14854). Ich hab ersteres jetzt mal deaktiviert, wenn letzteres aktiv ist, dadurch sollte das jetzt funktionieren.

**Comment by joriki** [comment]
Ah, vielleicht erklärt das auch, warum bei mir ab und zu der CKEditor nicht funktioniert hatte -- das hatte ich nicht als Bug gemeldet, weil es online nicht aufzutreten schien.

**Comment by joriki** [comment]
Das Problem besteht nach wie vor (sowohl bei mir lokal als auch online bei https://bdk-test2.antragsgruen.de).

**Comment by CatoTH** [comment]
Sicher auch nachdem der Cache geleert wurde? Ich hatte das bei bdk-test2.antragsgruen.de auch, bis ich es nochmal explizit geleert bzw. mit geöffneten Developer-Tools neu geladen habe.

Falls es immer noch passiert: was kommen denn für Meldungen in der JS-Konsole? (Am besten vorher das "Preserve Log" aktivieren)

**Comment by joriki** [comment]
Ah, sorry, nein -- den Cache hatte ich nicht geleert -- jetzt funktioniert es, wenn ich paste -- wenn ich den Content von JavaScript setze, funktioniert es immer noch nicht, aber das ist dann wohl ein anderes Problem -- ich schreib Dir dazu eine getrennte Mail und schließe das hier wieder.
