### ISSUE TITLE
"Änderungsantrag auf dieser Basis" zeigt ÄA nicht

### ISSUE THREAD

**Issue by andi98** [CatoTH/antragsgruen#226]
Wenn ich als eingeloggter Admin bei einem freigeschalteten ÄA in der rechten Spalte auf "Neuer Änderungsantrag auf dieser Basis" klicke, bekomme ich nur das "leere" Formular zum Änderungsantrag stellen angezeigt. Der ursprüngliche Änderungsantrag, auf dessen Basis ich einen neuen Stellen möchte, wird nicht mehr angezeigt. Es wird lediglich das normale ÄA-Formular mit dem originalen Antragstext angezeigt.
Nur die Kontaktdaten des ursprünglichen ÄA-Stellers sind im Formular ausgefüllt.
M.E. müsste im Feld "Antragstext" der Änderungsantrag mit angezeigt werden und nicht nur der ursprüngliche Antrag.

Ich hoffe, das ist verständlich erklärt & nachvollziehbar. Wenn nicht, bitte einfach nachfragen :)

**Comment by CatoTH** [comment]
Hallo,
tatsächlich war das von demjenigen, der dieses Feature haben wollte, so gewollt (Hintergrund: es ging vor allem bei längeren Listen an Unterstützer*innen darum, sich die Tipparbeit zu ersparen, wenn diese mehrere ÄAs am Stück auf alternative Wege eingereicht haben). Brauchst du die Funktion mit den Änderungen? Wenn ja, kann ich das schon in der nächsten Version irgendwie mit einbauen, viel Aufwand wäre das nicht.

**Comment by CatoTH** [comment]
@andi98 bei der neuen Version ist es dann jetzt so, dass der Text bzw. die Änderungen standardmäßig übernommen werden und es nur noch bei ÄAs die Option "Änderungen rückgängig machen" gibt, falls es wirklich nur um die Personen unten geht.

**Comment by andi98** [comment]
@CatoTH Danke für die Implementierung! Leider funktioniert das bei uns aber noch nicht ganz so, wie du es beschrieben hast.
Ich habe diesen Antrag mit einem Änderungsantrag:
![screen shot 2017-10-12 at 13 19 35](https://user-images.githubusercontent.com/6323836/31493590-2ac3fcf4-af50-11e7-9da0-ca19664765f7.png)
Ich klicke jetzt auf "Neuer ÄA auf dieser Basis" und komme dabei auf diese URL: `https://www.example.com/test/Test-54590/amendment/create?cloneFrom=708`
Da sehe ich jetzt dieses Formular, also wieder nur mit dem originalen Antrag und nicht dem Änderungsantrag.
![screen shot 2017-10-12 at 13 22 05](https://user-images.githubusercontent.com/6323836/31493650-663a5d64-af50-11e7-941d-31caec2667c9.png)

Kann das ein Bug sein oder habe ich einen Denkfehler?

**Comment by andi98** [comment]
Hallo @CatoTH, hast du vielleicht eine grobe Idee, woran das liegen könnte? Ich habe mir gerade deinen Commit 4c37659 angeschaut und debuggt, da sieht alles gut aus. Also die Daten werden bis zur Funktion `cloneAmendmentText` durchgereicht und im `$form` auch geändert. Allerdings wird nicht das richtige Formular angezeigt... ich bin etwas ratlos :/

**Comment by CatoTH** [comment]
@andi98 Hast du evtl. irgendwo eine einsehbare Installation, wo ich mir das anschauen kann? Weil bei meiner lokalen Version funktioniert das irgendwie schon...

**Comment by andi98** [comment]
@CatoTH Habe ich dir gemailt.

**Comment by CatoTH** [comment]
@andi98 Probier mal, ob der Commit hier https://github.com/CatoTH/antragsgruen/commit/957cf79af05238e9d764a2286cca9bd5198cf5bf das Problem löst. Ich hoffe mal.

**Comment by andi98** [comment]
@CatoTH Hervorragend, funktioniert! Vielen lieben Dank :)
