### ISSUE TITLE
bei Beschränkung auf einen Absatz werden trotzdem andere Änderungen markiert

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#227]
Bei aktivierter Option, dass nur ein Absatz geändert werden kann:

- Absatz zum Ändern auswählen
- (ggf. Änderungen vornehmen, oder auch nicht)
- "Änderungen rückgängig machen" wählen
- anderen Absatz auswählen

Jetzt ist der neu ausgewählte Absatz aktiv; darin kann man normal editieren, und diese Änderungen werden nachher als Antrag gespeichert. In dem zuerst ausgewählten Antrag kann man aber immer noch streichen und formatieren, nur nicht mehr einfügen. Diese Änderungen werden aber nur markiert; sie erscheinen nachher nicht im Antrag.

**Comment by CatoTH** [comment]
Danke für den Hinweis! Das sollte jetzt behoben sein.
