### ISSUE TITLE
Datum der Einreichung scheint falsch angezeigt zu werden

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#228]
Ich habe mehrmals Mails mit Bitte um Unterstützung gekriegt, und wenn ich auf die Links geklickt hab, wurde hinter "Eingereicht:" ein Datum weit vor dem Datum der Mail angezeigt. Ich vermute, das ist das Datum des Anlegens und nicht des Einreichens?

Ein Beispiel:
https://antraege.gruene.de/bdk41/Wir_sorgen_fuer_Sicherheit_und_erhalten_die_Freiheit_-40164/672
Da steht "Eingereicht: 14.04.2017, 22:03", aber am 24. April wurde noch eine Mail mit Bitte um weitere Unterstützung rumgeschickt.

**Comment by CatoTH** [comment]
Ich hab jetzt (bei der kommenden Version) eingebaut, dass das Datum beim offiziellen Einreichen aktualisiert wird. Das Wording unterscheidet nun auch, ob der Antrag schon offiziell eingereicht ist, oder nur "angelegt".
