### ISSUE TITLE
Nach Fettschrift in Begründung alle weiteren ÄAs in Fettschrift

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#229]
In der aktuellen Sammlung aller Änderungsanträge (https://antraege.gruene.de/bdk41/amendment/pdfcollection) sind ab S. 449 alle Änderungsanträge in Fettschrift. Das scheint damit zusammenzuhängen, dass in UK-WU-01-115-2 auf S. 448 die Begründung in Fettschrift ist.

**Comment by CatoTH** [comment]
Ich hab jetzt erst mal die Fettschrift rausgenommen, da sie inhaltlich ohnehin eher nicht wie gewollt aussah und damit der PDF-Export erst mal wieder richtig funktioniert. Heute Abend schau ich, dass ich den PDF-Exporter dann so anpasse, dass dieses Problem auch mit Fettschrift nicht mehr auftritt.
