### ISSUE TITLE
Support multi site mode on single Domain

### ISSUE THREAD

**Issue by derSascha** [CatoTH/antragsgruen#233]
Hi,

gibt es eine Möglichkeit mehrer Veranstaltungen unter der gleichen Domain zu hosten?

Also:
www.example.org/conf-01
www.example.org/conf-02...

Ich habe in der `config.json` folgendes:
```
  "siteSubdomain": "www",
  "prettyUrl": true,
  "multisiteMode", true,
  "domainPlain": "https://www.example.org/",
  "domainSubdomain": "https://<subdomain:[\\w_-]+>.example.org/",
  "prependWWWToSubdomain": false
```

Auf der Startseite ( www.example.org/ ) werden die Veranstaltungen jetzt aber nicht gelistet. Gibt es da einen Trick?

**Comment by CatoTH** [comment]
Leider kommt das jetzt von meiner Seite ziemlich spät. Zum Multi-Site-Mode gibt es jetzt in der README einige Hinweis: https://github.com/CatoTH/antragsgruen#multisite-mode 
Vielleicht lag es beim Beispiel oben an der siteSubdomain.
Grundsätzlich geht es natürlich auch ohne Multisite-Modus, mehrere Veranstaltungen auf einer Seite zu betreiben - Multisite braucht man nur, wenn man mehrere Organisationen hosten will, die selbst jeweils unabhängig voneinander mehrere Veranstaltungen verwalten sollen.
In der Sidebar der Startseite werden allgemein alle Seiten gelistet, die in den letzten 3 Monaten angelegt wurden und nicht mehr im Wartungsmodus sind.
