### ISSUE TITLE
ODS-Export von Änderungsanträge enthalt Verfahren nicht

### ISSUE THREAD

**Issue by andi98** [CatoTH/antragsgruen#234]
Wenn ein Spreadsheet der Änderungsanträge exportiert wird, existiert doch leider keine Spalte mit dem aktuellen Verfahren, das unser Ansicht nach da aber reingehören müsste.

Wir haben da schon einen Bugfix entwickelt, den stelle ich gleich mal als Pullrequest.

**Comment by andi98** [comment]
Okay, ich kriege gerade irgendwie keinen vernünftigen Pull request hin. Hier die notwendige Änderung. 
[234.diff.txt](https://github.com/CatoTH/antragsgruen/files/1340586/234.diff.txt)

**Comment by CatoTH** [comment]
Hallo,
ich würde den Status wenn dann als neue Spalte mit aufnehmen, da der aktuelle Status doch etwas anderes ist als der Verfahrensvorschlag, der in der 3.7er-Version noch nicht im System gepflegt werden kann und deswegen freigelassen wird fürs händische Ausfüllen. (In 3.8 wird es dann die Möglichkeit geben, den Verfahrensvorschlag auch direkt in Antragsgrün einzugeben).
Ich würde das dann mit neuer Spalte am Wochenende für die Version 3.7.1 einbauen. Ihr müsstet dann halt die leere Verfahrensvorschlag-Spalte löschen, wenn ihr sie nicht braucht, ist aber denk ich trotzdem das sinnvollste.

**Comment by CatoTH** [comment]
Ich hab das jetzt in der neuen 3.7.1 so eingebaut, als extra Spalte. Ich hoffe, das ist so etwa in eurem Sinne.
