### ISSUE TITLE
Error: #2 

### ISSUE THREAD

**Issue by FMCumhaill** [CatoTH/antragsgruen#237]
Hey, 
Installed antragsgruen  using the pre-bundled package. Ran the install process and it worked fine but redirected to this page. 

I can't view the home page now? 

![capture](https://user-images.githubusercontent.com/31923535/33240869-f26b9fc4-d2bd-11e7-9ad0-f29d7bac2c0a.PNG)

**Comment by CatoTH** [comment]
@FMCumhaill Can you maybe check if there is a file ``runtime/logs/app.log`` and  send me the contents of it? (tobias@hoessl.eu)

**Comment by FMCumhaill** [comment]
Emailed! Thanks for the quick response

**Comment by FMCumhaill** [comment]
Error was in the messages/en/con.php file. File was named _con.php  

Renamed to con.php (Removed underscore) and problem solved. 

Thanks to @CatoTH  for the super quick support.
