### ISSUE TITLE
Das Einfügen eines Umlauts wird im Editor nicht als Änderung angezeigt

### ISSUE THREAD

**Issue by MarcelWaldvogel** [CatoTH/antragsgruen#238]
Änderungsantrag stellen->im Antragstext einen Umlaut einfügen (getestet mit "ü" und "ä"): Dieser wird hier nicht als Einfügung grün hinterlegt. Im nach dem Einreichen dargestellten Diff wird das Wort korrekt als geändert angezeigt.

**Comment by CatoTH** [comment]
Das müsste inzwischen behoben sein, vermutlich mit einem der letzte Updates des Editors. Oder tritt es bei dir noch auf?
