### ISSUE TITLE
bdk.antragsgruen.de sollte immer auf aktuelle BDK linken

### ISSUE THREAD

**Issue by gerbsen** [CatoTH/antragsgruen#239]
Hallo,
Können wir es irgendwie hinbekommen, das auf dem Laufenden zu Halten? Ich komm bei den vielen verschiedenen Versionen leider etwas durcheinander.

Viele Grüße,
Daniel

**Comment by CatoTH** [comment]
Ich hab jetzt mal einen Link auf antraege.gruene.de eingefügt. Der Bundesverband hat ja inzwischen seine eigene Installation, deswegen ist bdk.antragsgruen.de nur noch ein Archiv - einfach umleiten will ich es halt auch nicht, da sonst die alten BDK-Versionen verloren gehen würden.
