### ISSUE TITLE
Kontaktdaten vom Login unabhängig machen

### ISSUE THREAD

**Issue by CatoTH** [CatoTH/antragsgruen#24]
Die Felder organisation, telefon und email sollten aus der Tabelle person raus und stattdessen in antrag_unterstuetzerInnen bzw. aenderungsantrag_unterstuetzerInnen gespeichert werden.

**Comment by stuffmc** [comment]
@CatoTH und was ist mit https://github.com/CatoTH/antragsgruen/issues/914? :) Danke.
