### ISSUE TITLE
Creating a new user from the admin page, does not set the user's email address in the db

### ISSUE THREAD

**Issue by sksksksk** [CatoTH/antragsgruen#241]
I use the text fields in the user admin page (a text area for the emails and another one for the names) to create a new account.

After creating the account, I tried to use the "forgot password" functionality to reset the password, but got an error that it was trying to send an email to a NULL address.

Looking into the user table in the database I saw that the row of the newly created user has an empty (NULL) value for the email attribute. The email is correctly set in the auth attribute.

Shouldn't  the email attribute be set when a new user is created? If the user, for any reason, does not get the email with the password, he is not able to login to set his email address.

I use version 3.7.5

**Comment by CatoTH** [comment]
Thanks for reporting this! I fixed it in https://github.com/CatoTH/antragsgruen/commit/e21c973213a1dc7a5296184b69079ae196fe64c3#diff-a614dbf902d7ec894def9f2c319634c8R93 (only line 93 is really relevant), the fix will be included in v3.8.
