### ISSUE TITLE
Problem mit mehrseitigen individuellen PDFs 

### ISSUE THREAD

**Issue by andi98** [CatoTH/antragsgruen#242]
Hallo!

Wenn man individuelle PDFs (für Bewerbungen) zulässt und für den Antragstypen die PDF-Generierung nicht deaktiviert, passiert so etwas: https://bv.antrag.gruene-jugend.de/buko49/Ricarda_Lang-24332/pdf (beachtet die dritte Seite).

Insgesamt fände ich es bei individuellen PDFs cooler, wenn der Link zur PDF-Version einfach direkt zum individuellen PDF führt und gar kein neues PDF generiert wird.

Oder gibt's vielleicht Fälle, wo das Sinn macht? Wir haben es bisher nicht wirklich gebraucht.

Liebe Grüße,
Andi

**Comment by macwinnie** [comment]
Hallo Andi,
Wenn wir das AntragsGrün bei uns im Verband einsetzen, dann zu unsren Mitgliederversammlungen. Da ist es am Ende der Sitzung für alle Beteiligten eine enorme Erleichterung, einen einzelnen Knopf zu drücken und ein gesamt-PDF zu erhalten – mit allen Anträgen und ggf. eben auch Dateiuploads an der genau richtigen Stelle. Das PDF geht dann auch immer genau so ans Amtsgericht als Anhang zum Protokoll.
Es kommt genauso vor, dass ein Antrag zusätzlich zum individual-Antrag auch noch andere Abfragen enthält, die eine automatisierte Weiterverarbeitung erleichtern. Auch dann sollte nicht nur das Individual-PDF angezeigt werden, sondern eben dieses in das Antrags-PDF eingebettet werden.
Und selbst ein Fall wie von dir aufgezeigt würde in unserem Fall unter Umständen die Einbettungsvariante erfordern: damit auf dem Beiblatt die Upload-Zeit dokumentiert ist und die entsprechenden Stellen ihrer Dokumentationswut genüge getan sehen.
Trotz dieser Szenarien verstehe ich dein Anliegen. Idee (mit höherem Umsetzungsaufwand): wenn der Dateiupload das einzige ausfüllbare Element eines Antrags ist, könnte man eine Option anbieten, nur das Quell-PDF anzuzeigen, sonst aber das bisherige, korrigierte Verfahren befolgen. Oder genau andersrum und eine Checkbox für „Deckblatt inkludieren“ anbieten.
So viel gerade von mir dazu,
Beste Grüße,
Martin

**Comment by CatoTH** [comment]
Ich schau mal, ob ich den konkreten Bug mit der Seite die Tage beheben kann.
Ansonsten fände ich eine Einstellung bei den Antragstypen schon auch ok, mit der man für solche Typen das individuell hochgeladene PDF zum "Haupt-PDF" erklärt.

**Comment by CatoTH** [comment]
@andi98 Der Commit hier sollte das Problem mit der Überlagerung eigentlich lösen: https://github.com/CatoTH/antragsgruen/commit/fc0cfd59293b6b2e162f2ad4b71943d99aabc3d1

**Comment by CatoTH** [comment]
@andi98 Reicht euch dieser Fix eigentlich so, oder wäre es euch trotzdem lieber, wenn es eine deckblattlose Version gäbe? Die müsste ich dann halt noch einbauen...

**Comment by andi98** [comment]
@CatoTH Der Fix reicht uns so, danke dir!
