### ISSUE TITLE
Spreadsheet-Export schlägt fehl

### ISSUE THREAD

**Issue by andi98** [CatoTH/antragsgruen#243]
Hallo,

in der aktuellen Beta 3.8.0 habe ich das Problem, dass beim Spreadsheet-Export der Änderungsanträge fehlschlägt mit der Begründung "Unknown Tag: small".
Ein kurzer Blick in den Code hat gezeigt, dass es wohl so aussieht, als würde irgendwo <small> als HTML-Tag in einem Antrag vorkommen und deswegen der Export abbrechen.
Es wäre wahrscheinlich besser, die unbekannten HTML-Tags einfach zu entfernen, statt den Export abzubrechen, oder?

Bei mir tritt es übrigens nur auf, wenn ich das Häkchen "inaktive" setze. Habe aber jetzt nicht überprüft, um welchen Antrag es genau geht und wo der dazugehört.

**Comment by CatoTH** [comment]
Hi!

Es ist es etwas seltsam, dass es SMALL überhaupt rein geschafft hat - das sollte eigentlich schon bei der Eingabe herausgefiltert werden.
Ich hab jetzt aber den Spreadsheet-Export so angepasst, dass unbekannte Tags einfach als Inline-Text behandelt werden. Ich schau, dass ich eine neue Beta-Version dieses Wochenende zusammenstelle.
