### ISSUE TITLE
"View changes" funktioniert nicht

### ISSUE THREAD

**Issue by andi98** [CatoTH/antragsgruen#244]
Wir testen gerade die neue Beta2 von 3.8.0 und sind alle total begeistert von den neuen Verfahrensvorschlägen und modifizierten Übernahmen! Sehr cool gelöst.

Leider funktioniert nur die Funktion "Änderungen anzeigen" zwischen zwei Antragsversionen bei uns nicht. Ist das ein bekanntes Problem in der Beta oder habe ich vielleicht das Feature nicht ganz richtig verstanden? Um diese Seite geht's: [https://bv.antrag.gruene-jugend.de/gjbuko50/motion/735/view-changes]()

**Comment by CatoTH** [comment]
@andi98 Das war leider ein Bug, der nur dummerweise aus Zufall in meinem Testsystem nicht zum tragen kam... eine einfache Änderung wie in https://github.com/CatoTH/antragsgruen/commit/0e64ba9a3bf00efb96d755ce413d41679d7bdb25 beschrieben müsste das beheben.
