### ISSUE TITLE
Veranstaltungsadmins lassen sich nicht löschen

### ISSUE THREAD

**Issue by andi98** [CatoTH/antragsgruen#246]
Hallo!

Wir haben in der 3.8.0-RC1 das Problem, dass zwar das Hinzufügen von weiteren Admins zur Veranstaltung funktioniert, das Löschen oder Ändern der Berechtigungen aber nicht. Es geht um den Punkt "Login / Benutzer*innen / Admins" in den Einstellungen.
Wenn ich auf das Symbol klicke kommt eine Sicherheitsabfrage, ich klicke auf "akzeptieren", die Seite lädt neu, aber die Person ist immer noch da.

Ist kein akutes Problem bei uns, ich hab mich nur in einer Mailadresse vertippt, da ist es mir aufgefallen :D

**Comment by CatoTH** [comment]
Ich hab den Fehler jetzt gefunden - war wohl ein Browser-spezifisches Problem. Ich schau, dass ich zeitnah noch ein 3.8.1 nachschiebe, in dem das dann behoben ist.
