### ISSUE TITLE
Userlist und Siteconfig werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by MichaelZiegler** [CatoTH/antragsgruen#250]
Bei meiner Antragsgrün-Installation werden die Seiten "Userlist" und "Siteconfig" nicht mehr im Menü "Einstellungen" angezeigt. Auch über direkte Links scheine ich diese Seiten nicht mehr aufrufen zu können.
Möglicherweise hängt das Problem damit zusammen, dass ich die (Sub)Domain der Installation geändert habe. Erst danach ist mir das Problem aufgefallen.
Hatte jemand schon mal ähnliche Probleme und ist eine Lösung bekannt?

**Comment by MichaelZiegler** [comment]
Sorry, dass ich erst jetzt antworte, nachdem der Thread geschlossen ist. Irgendwie ist mir die erste Antwort durchgegangen.
Allerdings steht die ID meines Users bei _AdminUserId_, aber dennoch werden die Links nicht angezeigt. Darf es mehr als einen AdminUser geben?

**Comment by CatoTH** [comment]
Ja die IDs können auch kommagetrennt sein. Letztlich müsste man wohl wirklich schauen, wo der Fehler konkret liegt. In der Funktion currentUserIsSuperuser() in models/db/User.php müsste man mal schauen, was bei 
```php
var_dump($user->id); var_dump($params->adminUserIds);
```
so kommt. Im korrekten Fall müssten beides aus den selben User-IDs bestehen...
