### ISSUE TITLE
sendmail nicht msmtp kompatibel

### ISSUE THREAD

**Issue by macwinnie** [CatoTH/antragsgruen#252]
Hi @CatoTH,

da ich in einem Docker-Container keinen vollständigen Mailserver laufen lassen und die Konfiguration so gering wie möglich halten möchte, kommt im Docker-Image [jugendpresse/docker-antragsgruen](https://hub.docker.com/r/jugendpresse/docker-antragsgruen) das Paket `msmtp` zum Einsatz, welches auch das `sendmail`-Kommando ersetzt.

Leider gehen dabei dann ein paar Parameter von `sendmail` verloren – so dass ein E-Mail-Versand aus AntragsGrün via `sendmail` zu folgender Fehlermeldung führt:

```
sh: 1: -t: not found
```

`-t` als Parameter beim regulären `sendmail` extrahiert die Empfänger aus den E-Mail-Headern. Wo kommt das denn bei AntragsGrün zum Einsatz und warum ist das notwendig? Kann man da drauf (einfach) verzichten, so dass hier schnell und einfach eine Kompatibilität geschaffen werden kann?

Danke dir und viele Grüße,
Martin

**Comment by CatoTH** [comment]
Der Parameter dürfte eher aus der php.ini kommen - konkret wohl die Option ``sendmail_path`` (vgl. http://php.net/manual/de/mail.configuration.php).

**Comment by macwinnie** [comment]
Hi @CatoTH,
stimmt – auf die ini bin ich nicht gekommen ... bei der Recherche sind mir immer nur Framework-Implementierungen über den Weg gelaufen. Fehler erkannt, Image wird angepasst =)
Viele Grüße,
Martin
