### ISSUE TITLE
issue in Windows environment

### ISSUE THREAD

**Issue by GaneshKandu** [CatoTH/antragsgruen#254]
Hi,

Getting Error after install antragsgruen 3.8.2
messages\*\con.php is missing from extracted zip
con.* file is invalid in windows, windows not allowed to create such file
that's why con.* files are missing in extracted zip and i am getting error after install
[http://www.thewindowsclub.com/create-restricted-files-folders-con-aux-nul-click-windows](http://www.thewindowsclub.com/create-restricted-files-folders-con-aux-nul-click-windows)

**Comment by CatoTH** [comment]
Hi!
Thanks for the report! I just published a 3.8.3-release that addresses this issue. Can you confirm it works now?
Bye,
  Tobias

**Comment by GaneshKandu** [comment]
@CatoTH  Works Thanks ! :tada:
