### ISSUE TITLE
Fehler bei Sammel-PDFs

### ISSUE THREAD

**Issue by andi98** [CatoTH/antragsgruen#263]
Hallo zusammen!

Wenn ich bei uns auf der Seite rechts in der Sidebar alle Bewerbungen als ein PDF herunterladen will, erhalte ich folgende Fehlermeldung:

`Error: Exception: This document (VarStream://0) probably uses a compression technique which is not supported by the free parser shipped with FPDI. (See https://www.setasign.com/fpdi-pdf-parser for more details) in /var/www/vendor/setasign/fpdi/pdf_parser.php:322 `

Die Fehlermeldung sagt ja eigentlich schon, wo das Problem liegt: eine der hochgeladenen PDF-Bewerbungen hat eine zu neue PDF-Version und kann deswegen wohl von FPDF nicht verarbeitet werden.

Gibt's irgendeine Möglichkeit das zu umgehen? Angenommen wir würden wir Lizenz für das kommerzielle FPDF-Plugin kaufen, ließe sich das einfach in AG einbinden?

Danke schonmal :)

**Comment by CatoTH** [comment]
Das hier fängt den Fehler ab und gibt stattdessen eine Fehlermeldung im PDF aus: https://github.com/CatoTH/antragsgruen/commit/39b940e26371751a2413657ed9b656246b2e244b
Falls ihr das Plugin doch noch braucht, sagt Bescheid.
