### ISSUE TITLE
Nummerierungsart unterstützen

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#269]
Im Antragstext-Editor kann man mit Rechts-Klick auf ein Listen-Item ein Menü aufrufen, in dem man die Nummerierungsart (klein/groß, römisch/arabisch/Buchstaben) einstellen kann; aber wenn man den Antrag nachher aufruft, ist alles auf arabische Zahlen umgestellt.

**Comment by CatoTH** [comment]
Perspektivisch wäre es natürlich tatsächlich nett, wenn die Nummerierungsarten unterstützt würden. Ist leider wohl etwas Arbeit, das in den beiden PDF-Rendering-Methoden sowie -OpenDocument-Varianten abzubilden. Deshalb hab ich es vorerst aus dem CKEditor rausgenommen.

**Comment by CatoTH** [comment]
Die Funktion ist nun im Master-Branch gelandet und wird mit der nächsten größeren Version (4.6) veröffentlicht.
