### ISSUE TITLE
Seite nicht gefunden

### ISSUE THREAD

**Issue by Sizoberz** [CatoTH/antragsgruen#276]
Jetzt habe ich doch noch Probleme ...
Alles funktioniert, nur die zwei Links in den Einstellungen
"Registrierte Benutzer*innen"
Link: https://www.gruen-burladingen.de/antragsgruen/web/index.php?r=admin%2Fuserlist&consultationPath=kick-off
und "Konfiguration der Antragsgrün-Installation"
Link: https://www.gruen-burladingen.de/antragsgruen/web/index.php?r=admin%2Fsiteconfig&consultationPath=kick-off
funktionieren nicht

Fehler:
Not Found (#404)
Seite nicht gefunden.

The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you.

**Comment by CatoTH** [comment]
Hallo,

ich hab beide Fehler (bei der Installation unddas hier) jetzt behoben (https://github.com/CatoTH/antragsgruen/commit/9c8ccf57f334c6c60d364751e34924ed5987faa7). Das wird dann im nächsten Release Candidate bzw. in der finalen Version dann enthalten sein.
