### ISSUE TITLE
Titellöschung in Änderungsantrag verschwindet zu unerwarteter Zeit

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#277]
Wenn ein Änderungsantrag den Titel des Antrags geändert hat und man unter "Admin: Bearbeiten" den neuen Titel löscht, das Titel-Feld leer lässt und speichert, wird zunächst der leere Titel gespeichert und in der Darstellung des Änderungsantrags angezeigt ("Titel / Ändern in:", ohne Titel dahinter). Wenn man dann aber wieder "Admin: Bearbeiten" wählt, wird keine Titeländerung mehr angezeigt, und wenn man "Speichern" wählt, ohne selbst etwas geändert zu haben, wird der Änderungsantrag ohne Titeländerung (also nicht mehr mit leerem, sondern mit ungeändertem Titel) gespeichert.

Es könnte durchaus Sinn machen, das Löschen des Titels als Wiederherstellen des alten Titels zu interpretieren; das sollte aber wenn, dann gleich passieren, nicht unerwartet beim erneuten Bearbeiten.

**Comment by CatoTH** [comment]
Ok, das wird jetzt behoben. Es war übrigens gar nicht nötig, es nochmal zu speichern, damit das verschwindet, es verschwand auch schon beim Neuladen der Bearbeiten-Seite.
