### ISSUE TITLE
Installation routine does not work

### ISSUE THREAD

**Issue by errotu** [CatoTH/antragsgruen#293]
I tried to install your software on my webspace by following the instructions in the ReadMe. After entering the credentials for the MySQL-database in the first screen, saving it and completely setting up the first motion, I'm thrown back to the first screen where I have to fill in the credentials again. At the moment it's an infinite loop.

Any ideas what the mistake might be? I already checked the config/config.json. The credentials I filled in have been stored there successfully.

Thanks a lot in advance for your help!

**Comment by thoessl** [comment]
By entering the credentials, you mean the installation page, or a regular login screen?
If it's the installation page, can you maybe check if there exists INSTALLATION file in the config folder?

**Comment by errotu** [comment]
That's  a quick reply, thank you!

I meant the installation page.
There is an "INSTALLING"-file in the config folder. I renamed it (to make it inaccessible) and get now the following error (in German) when accessing the antragsgrün-installation via web browser:

> FEHLER
>
> Keine Seite angegeben. Das dürfte ein Fehler bei der Installation sein.

**Comment by CatoTH** [comment]
I suppose, there could have been a problem when initializing the database. Can you have a look in the database, if there are tables? It should be about 32 of them. (The error log is in runtime/logs/app.log. It should say something about missing tables in that case)

**Comment by errotu** [comment]
That doesn't seem to be the problem. There are 32 tables in the database and the runtime-folder is empty except for a cache-folder and a .htaccess-file.

This is a screenshot (German) of the installation page after I already went through the installation (and the setup for the first motion) once:
![antragsgruen-error](https://user-images.githubusercontent.com/12113437/45473323-0df45200-b737-11e8-92f3-20d37f15e73f.png)

As the "Admin Zugang"-field states

> Bereits angelegt.
> Falls das ein Fehler ist: entferne die "adminUserIds"-Einträge in der config/config.json. 

and the "Passwort"-field:
> unverändert lassen

it seems like there is a general access to the database.

**Comment by errotu** [comment]
Of the 32 tables there are only three with rows:
migration (38 rows)
texTemplate  (2 rows)
user (1 row)

**Comment by thoessl** [comment]
And no entry in site?

**Comment by errotu** [comment]
Yes, no entry.

**Comment by thoessl** [comment]
Hm, maybe you can completely delete all tables, and perform the installation once more. If the same thing happens again, can you send me a screenshot of the first screen with an error message (if there is any) and the choices you made during the wizard and the contact form? Maybe there is a certain combination of values that prevents the site from being created...

**Comment by errotu** [comment]
One more thing I noticed:
I access the antragsgrün-Installation via: subdomain.domain.com, nevertheless, the entry in the config.json is:
>    "siteSubdomain": null,
>    [...]
>    "domainPlain": "https:\/\/subdomain.domain.com\/",
>    "domainSubdomain": "",

Is this correct? I'm wondering because of the "siteSubdomain" and "domainSubdomain" values.

**Comment by thoessl** [comment]
There seems to be some problem creating the site entry, that also explains the missing information config.json. Remote databases shouldn't be a problem, though. Do you know which version of MySQL is installed?
I'll try to figure out possible complications later this day.

**Comment by errotu** [comment]
I tried it on a different webspace (different hoster as well) and the same behavior occurred. Here I used a local MySQL-database. For accessing the database I had to enter the port used by localhost (which was the default port: 3306) which is kind of unusual when using graphical installers, I'd say.

**Comment by CatoTH** [comment]
I'm afraid I'm a bit lost without actually seeing it. I tried it and didn't see any problem. Maybe you could provide me with the url so I can see it myself? (by e-mail to tobias@hoessl.eu)
Alternatively, I can provide you a mysql dump file of a fresh installation so you can skip the installation; though I'm interested in the source of this problem as well.

**Comment by errotu** [comment]
I've sent you an e-mail with further information. Thanks a lot for your help!

**Comment by errotu** [comment]
@CatoTH found the problem! Thanks a lot!

The specification of a port doesn't work correctly at the moment. Nevertheless, under regular circumstances setting isn't needed, "localhost" (or the remote IP) without a specified port does what it should.
