### ISSUE TITLE
Open Document Export

### ISSUE THREAD

**Issue by errotu** [CatoTH/antragsgruen#306]
Bei mir funktioniert Open Document Export leider nicht. Wenn ich in der Antragsliste auf den ODT-Export klicke oder über "Verfahrensvorschlag" -> "ODS Export: Alles" gehe, zeigt mir der Browser jeweils nur die folgende Meldung an:

>Fehler: Datei nicht gefunden
>
>Beim Verbinden mit mitmachen.spd-heidelberg.de trat ein Fehler auf.
>
  >  Bitte überprüfen Sie die Adresse auf Rechtschreib-, Groß-/Kleinschreibungs- oder andere Fehler.
Bitte überprüfen Sie, ob die Adresse umbenannt, gelöscht oder verschoben wurde.

Gibt es bestimmte Voraussetzungen, die für den ODT-/ODS-Export erfüllt werden müssen?

Die verwendete Version ist 4.0.2, das verwendete Template basiert auf [gruen_ci](https://github.com/CatoTH/antragsgruen/tree/master/plugins/gruen_ci).

Vielen Dank schon mal vorab für die Hilfe!

**Comment by thoessl** [comment]
Hallo,
funktionieren denn die anderen ODS/ODT-Exports, oder ist das nur der eine, der nicht funktioniert?

**Comment by errotu** [comment]
Hey, die ODT-Exports funktionieren leider alle nicht. Zwei der ODS-Exports funktionieren interessanterweise: Export -> Kapitel -> Spreadsheet sowie Export -> Änderungsanträge -> Spreadsheet.

**Comment by thoessl** [comment]
Kannst du mir vielleicht die letzten Meldungen aus der runtime/logs/app.log an tobias@hoessl.eu schicken, oder die gesamte Datei? Darin sollten die genauen Fehlermeldungen festgehalten werden.

**Comment by CatoTH** [comment]
Zwei der drei Probleme sollten im eben veröffentlichten 4.0.4 behoben sein. Beim dritten hatte ich dir ja geschrieben, woran es liegt.

**Comment by errotu** [comment]
Vielen Dank für die Hilfe, jetzt funktioniert alles!
