### ISSUE TITLE
Styling ausschließlich über Themes

### ISSUE THREAD

**Issue by errotu** [CatoTH/antragsgruen#311]
Hallo,

mir ist gerade aufgefallen, dass in der [_view_sidebar.php](https://github.com/CatoTH/antragsgruen/blob/master/views/motion/_view_sidebar.php#L42) inline-Styling verwandt wird. Das erschwert das Anpassen in Custom Themes. Würde deshalb vorschlagen, dass das Styling grundsätzlich nur über die Themes läuft, so dass man es dann unproblematisch modifizieren kann.

Oder gibt es einen bestimmten Vorteil am inline-Styling, den ich übersehen habe?

**Comment by CatoTH** [comment]
Nein, das hatte ich nur übersehen :)
