### ISSUE TITLE
BBCode loswerden

### ISSUE THREAD

**Issue by CatoTH** [CatoTH/antragsgruen#32]
Die Normalisierung des Texts dadurch vorzunehmen, dass man ihn in BBCode umwandelt, war wohl insgesamt eine eher schlechte Idee. Sinnvoller wäre eine möglichst strikt normalisiertes Subset von HTML mit nur den allernötigsten Tags und klarer Definition, wann Leerzeichen bzw. -zeilen vorkommen sollen und wo nicht.

**Comment by patrickhanft** [comment]
Hmm, ich würde ja für Markdown plädieren … ;-)
