### ISSUE TITLE
migration fails upgrading to 4

### ISSUE THREAD

**Issue by sksksksk** [CatoTH/antragsgruen#328]
I am trying to upgrade a 3.7.5 version to the latest. 
The migration step m180519_180908_siteTexts fails.
I tried the following upgrade paths
3.7.5->4.1.1
3.7.5->4.0.0
3.7.5->3.8.3->4.0.0
3.7.5->3.8.3->4.1.1

In all cases I get an error in migration m180519_180908_siteTexts
```
*** applying m180519_180908_siteTexts
    > add column siteId INT DEFAULT NULL AFTER consultationId to table consultationText ... done (time: 0.039s)
    > add column title TEXT DEFAULT NULL AFTER textId to table consultationText ... done (time: 0.032s)
    > add column breadcrumb TEXT DEFAULT NULL AFTER title to table consultationText ... done (time: 0.031s)
    > create index consultation_text_site on consultationText (siteId) ... done (time: 0.019s)
    > add foreign key fk_consultation_text_site: consultationText (siteId) references site (id) ... done (time: 0.032s)
Exception: Getting unknown property: app\models\db\ConsultationText::menuPosition (/home/www/xxxx/vendor/yiisoft/yii2/base/Component.php:154)
#0 /xxxx/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\base\Component->__get('menuPosition')
#1 /home/www/xxxx/vendor/yiisoft/yii2/validators/Validator.php(264): yii\db\BaseActiveRecord->__get('menuPosition')

```

**Comment by CatoTH** [comment]
Unfortunately, upgrading from 3.* to 4.* really is a bit awkward sometimes, as the streamlined upgrade process was only added in 4.0.

The following steps should work around this problem with this migration:
First, confirm that the changes are made in the database - the `consultationText`-table should have a column called "breadcrumb", "title" and "siteId".
Then the following SQL-command:
```sql
UPDATE consultationText a JOIN consultation b ON a.consultationId = b.id SET a.siteId = b.siteId WHERE a.siteId IS NULL;
```
After that, you can mark the migration as done:
```bash
./yii migrate/mark m180519_180908_siteTexts
```

Sorry for the inconvenience. There might be another migration that has a similar problem, not sure. Starting with 4.0, things should be less troublesome.

**Comment by sksksksk** [comment]
great! This helped.

The 3 new columns had been already inserted. After running your query and marking the migration as done, the rest of the migrations worked without any problem.

Thanks! This ticket can be closed
