### ISSUE TITLE
Admin-Menü kann nicht mehr geöffnet werden

### ISSUE THREAD

**Issue by annawestner** [CatoTH/antragsgruen#329]
Habe eine Person aus den registrierten Benutzer_innen entfernt, da sie sich nicht einloggen konnte und wir das Konto neu erstellt haben. Die Person war zu dem Zeitpunkt aber noch als Admin/Moderator eingetragen. 
Seitdem kann das Login/Benutzer_innen/Admin-Menü nicht mehr geöffnet werden, es erscheint folgende Fehlermeldung: "Error (#1)
An internal server error occurred.
The above error occurred while the Web server was processing your request.
Please contact us if you think this is a server error. Thank you."

**Comment by CatoTH** [comment]
Hallo,
der Fehler wird in der nächsten Version behoben, die allerdings noch nicht veröffentlicht ist.
Hast du Zugriff auf den direkten Code der Antragsgrün-Installation? In dem Fall könntest du die Änderung von Hand einspielen, die das Problem behebt: nämlich in der Datei
`controllers/admin/SiteAccessTrait.php`
etwa bei Zeile 465 nach dieser Zeile:
`if (!isset($admins[$privilege->userId])) {`
folgenden Code einfügen:
`if (!$privilege->user) { continue; }`

**Comment by annawestner** [comment]
Hallo Tobias,

Hat funktioniert, vielen lieben Dank!
