### ISSUE TITLE
Anträge stellen und bearbeiten nicht mehr möglich

### ISSUE THREAD

**Issue by annawestner** [CatoTH/antragsgruen#331]
Nachdem das Problem, dass wir nicht mehr auf das Admin-Menü zugreifen konnten, gelöst wurde (Durch Einfügen einer zusätzlichen Zeile), können wir nun keine Anträge mehr stellen und bearbeiten.

Angezeigt wird jedes Mal folgende Fehlermeldung:
Error (#64)
An internal server error occurred.
The above error occurred while the Web server was processing your request.
Please contact us if you think this is a server error. Thank you.

Es geht um diese Website: https://lmv.linksjugend-bayern.de/antraege/web

**Comment by CatoTH** [comment]
Hallo,
könntet ihr mir den Inhalt der Datei runtime/logs/app.log schicken, am besten per E-Mail an tobias@hoessl.eu? Da müsste am Ende genauer stehen, was nicht stimmt...
