### ISSUE TITLE
Feature-Request: Stimmergebnisse eines Antragsbeschlusses vermerken

### ISSUE THREAD

**Issue by DBJRdev** [CatoTH/antragsgruen#335]
Am Ende von »Änderungsanträge einpflegen« bietet Antragsgrün bereits an, die einzelnen ÄA als übernommen etc zu markieren. Es wäre aber auch sehr nützlich, am Ende eintragen zu können, mit welchen Stimmergebnissen (Ja/Nein/Enthaltung) ein Gesamtantrag beschlossen bzw. abgelehnt wurde.

Über die Sichtbarkeit des Ergebnisses im Frontend gibt es sicherlich unterschiedliche Bedarfe, daher wäre die Anzeige am besten nur optional.

**Comment by arnebr** [comment]
“Auf Parteitagen selbst bietet sich der Einsatz von Tools an, die speziell dafür ausgelegt sind - wir empfehlen hier OpenSlides. (Antragsgrün bietet die Möglichkeit, Anträge und Änderungsanträge in Openslides zu exportieren.)”

Hier ist der Vermerk definitiv möglich, auch als Protokollexport.

**Comment by CatoTH** [comment]
Ja gut möglich. Ich denke mal, der Wunsch hier ist natürlich schon, dafür nicht noch ein zusätzliches Tool einsetzen zu müssen. :)

**Comment by arnebr** [comment]
Hallo Tobi,
das ist gut möglich, die Frage natürlich inwiefern es in die Software Philosophie passt. Hier kannst du wohl am meisten sagen ;)

LG von der Jugendpresse
Arne

**Comment by CatoTH** [comment]
Sollte in 4.3 nun soweit umgesetzt sein.
