### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by peduso** [CatoTH/antragsgruen#337]
Es ist ja möglich das Logo jeder Veranstaltung zu ändern. Das Logo wird aber nur angezeigt, wenn man eingelogged ist. Gibt es eine Möglichkeit das Logo grundsätzlich auf der landingpage neu zu setzen?

Antragsgrün, Version 4.1.1

**Comment by peduso** [comment]
![image](https://user-images.githubusercontent.com/2013114/52950172-9b8b3c00-337e-11e9-984e-5ab11696d3db.png)

**Comment by peduso** [comment]
hm, sorry, sollte  nicht zu gemacht werden.

**Comment by CatoTH** [comment]
Das ist tatsächlich ein Bug. Ich hab ihn eben behoben (https://github.com/CatoTH/antragsgruen/commit/4476037573705ecc2ae225be86a7539ff05f5084), und er wird in der nächsten Version (4.2) enthalten sein, die in ein paar Tagen erscheint.
