### ISSUE TITLE
Passwort zurücksetzen prüft Mails falsch und verschickt daher nicht

### ISSUE THREAD

**Issue by peduso** [CatoTH/antragsgruen#338]
Die Funktion das Passwort zu resetten führt zu einer Fehlermeldung. 
anscheinend wird die validität der Mailadressen nicht korrekt geprüft...
Version 4.1.1

![image](https://user-images.githubusercontent.com/2013114/52951130-3edd5080-3381-11e9-8396-f27eb01a24f3.png)

**Comment by CatoTH** [comment]
Hallo,

den Fehler hab ich jetzt so auf die Schnelle nicht reproduzieren können; geht es hier im wie im Screenshot gezeigt um den zweiten Schritt, oder um den ersten? Die Fehlermeldung passt nämlich eher zum ersten Schritt...

**Comment by peduso** [comment]
Hi, 
danke für die schnelle Antwort. 
Es ist beim ersten Schritt bereits. Mit der Fehlermeldung schiebt er meine Mailadresse ( von mir anonymisiert) in den zweiten Schritt.

Wenn ich es nochmal versuche, dann kommt folgende Fehlermeldung:

![image](https://user-images.githubusercontent.com/2013114/53017051-67338080-344f-11e9-83b1-36db8693d70d.png)

Es wird aber keine Mail verschickt. Haben wir bei der Einrichtung auf dem Server evtl. etwas zu bedenken?

**Comment by CatoTH** [comment]
@peduso Sorry dass ich so lange nicht geantwortet habe. Wenn ich es mir anschauen soll, kannst du mir vielleicht die Adresse eurer Seite an tobias@hoessl.eu schicken?

**Comment by peduso** [comment]
Hallo Tobias,

wir haben jetzt auf Version 4.2 aktualisiert. Vielleicht kannst du ihn auf unserer Seite (kjg) direkt anschauen. Was wären Möglichkeiten sich dem Problem zu nähern?

VG

**Comment by CatoTH** [comment]
@peduso eine Vermutung hatte ich ja per E-Mail geäußert - könntest du mal schauen, ob die Absender-E-Mail-Adresse auch richtig gesetzt ist? Falls die leer oder fehlerhaft ist, könnte evtl. das der Auslöser sein...

**Comment by peduso** [comment]
ah, hatte ich nicht mehr auf dem Schirm. Das scheint die Lösung zu sein. Immerhin bekomme ich jetzt eine andere Fehlermeldung. Jetzt muss ich nur noch klären was die korrekten Einstellungen sind, wenn ich office 365 als Absender nutzen will. 
Danke
