### ISSUE TITLE
Feature-Request: Taggen and filtern nach Tag für Anträge und Änderungsanträge

### ISSUE THREAD

**Issue by gerbsen** [CatoTH/antragsgruen#340]
Hallo,
Ich bin mir nicht 100% sicher, ob es das Feature in dieser oder einer anderen Form schon gibt. Ich hab [hier](https://antragsgruen.de/help) nichts gefunden, aber hier den [Issue](https://github.com/CatoTH/antragsgruen/issues/38). Mir wurde von Menschen in der Antragskommision herangetragen, dass es mitunter schwierig ist, gerade bei großen Mengen an Änderungsanträgen, bestimmte kritische Antrage wiederzufinden. Ich kann's aus Mangel an Erfahrung leider nicht selbst einschätzen (bin hier nur der Bittsteller ;)), aber es wäre denk ich gut, wenn man A/ÄA mit einem/mehreren Tags, z.B.: `kritisch`, `Tierschutz` markieren könnte, und dann in der späteren Arbeit im Kapitel auch nur diese angezeigt bekäme. (Übrigens, ich hab mir gerade versucht eine Sandbox Instanz zu klicken, da kam am Ende aber 400 Fehler?)
Viele Grüße, Daniel

**Comment by CatoTH** [comment]
Erst mal auf die Schnelle eine Antwort auf den leichteren Teil: der Bug mit der Sandbox ist jetzt behoben. (Rest folgt später)

**Comment by CatoTH** [comment]
...das war jetzt leider etwas sehr viel später...
Es kommt jetzt in der nächsten Version (4.8.0 - Pull Request dazu: https://github.com/CatoTH/antragsgruen/commit/18407e09fee6d88946623ccbe33ef09680df53c6) im Rahmen der Verfahrensvorschläge eine intern Tagging-Funktion, die auch zum Filtern in der Admin-Liste verwendet werden kann.
