### ISSUE TITLE
Upgrade from 4.1.1. to 4.2.0 via web-updater fails due to existing image2.js

### ISSUE THREAD

**Issue by DBJRdev** [CatoTH/antragsgruen#341]
We tried to upgrade via the web-updater from 4.1.1 to 4.2.0. However it fails with the following message

`The following files to be created already exist:

    web/js/ckeditor/plugins/image2/dialogs/image2.js
`

Once you delete/rename the existing file by hand, the web-based upgrade works.

**Comment by CatoTH** [comment]
Hm, I'm not sure where that file came from. It wasn't in 4.1.1 and 4.0.0 at least. Do you happen to still have that time, or the timestamp of when the file was created for that matter? If that happened on an installation path that was used before we installed the web-updater, it might be that the file existed in a previous version and was removed anywhere before 4.0.0 and was just lingering around...

**Comment by DBJRdev** [comment]
The redundant file had a timestamp of 2017-11-28 and 5209 bytes. There's no obvious version mentioned in the file, only "Copyright (c) 2003-2016, CKSource"

**Comment by CatoTH** [comment]
Given the date, I'm kind of sure that this was a relict from older installations from the pre-4.0-era. For installations that were installed starting 4.0, this should therefore not happen.
