### ISSUE TITLE
Einfachpasswort für eine Veranstaltung setzen: alle Veranstaltungen sind gesperrt

### ISSUE THREAD

**Issue by DBJRdev** [CatoTH/antragsgruen#361]
Kleiner Bug: In der 4.2.2 wurde eingeführt, dass man optional ein gemeinsames Passwort für alle Nutzer*innen einer Veranstaltung anlegen kann. Allerdings setzt man damit offenbar nicht nur ein Passwort für die aktuelle (Unter-)Veranstaltung, sondern immer auch für die Standardveranstaltung. Erst wenn man danach zur Standardveranstaltung wechselt und dort manuell das Passwort wieder entfernt, verhält sich Antragsgrün wie erhofft.

**Comment by CatoTH** [comment]
Ok stimmt, das ist wirklich nicht ganz klar so. Ich hab jetzt die Auswahl eingefügt, dass man es für alle Veranstaltungen oder nur die aktuelle setzen kann. Kommt mit dem nächsten Release.
