### ISSUE TITLE
Cleanup of __tcpdf_* files in /tmp

### ISSUE THREAD

**Issue by derSascha** [CatoTH/antragsgruen#368]
Hi,

antragsgruen erzeugt in `/tmp` sehr viele `__tcpdf_*` Dateien. Bei unserer installation sind das gerade mal eben ~4GB. Kann man die Dateien regelmäßig via z.B. cron löschen oder wofür sind die dort? Warum werden diese nicht automatisch von antragsgruen gelöscht?

Danke fürs antragsgruen entwickeln + Grüße
Sascha

**Comment by CatoTH** [comment]
Hallo,

sorry dass das jetzt etwas länger gedauert hat, ich war einige Wochen im Urlaub.
Ich kann das mit den Dateien bei mir auf Anhieb gerade nicht reproduzieren, da die Dateien hier automatisch wieder gelöscht werden. Ich vermute mal, die entstehen bei PDFs mit eingebetteten Bildern, oder? Entstehen die Dateien bei jedem Aufruf eines PDFs, oder evtl. nur bei einem, das nicht korrekt erzeugt werden konnte und dabei abstürzt?
