### ISSUE TITLE
Antragsfilter

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#38]
Es sollte möglich sein, die Anträge nach verschiedenen Kriterien zu filtern. Vor allem nach AntragstellerIn und Titel, sobald es TOPs gibt auch nach TOPs, am besten nach allen Feldern. (Im BGS-Antragstool ist das eine Admin-Funktion; es spricht aus meiner Sicht nichts dagegen, das für alle zur Verfügung zu stellen.)

**Comment by grafgraffy** [comment]
Hier mal ein Screenshot als "Mockup" vom BV Tool. Hier fehlt noch die Spalte Antragssteller. 
![screenshot adminoberflache resm tool](https://cloud.githubusercontent.com/assets/7473707/6726928/4d4f9ff6-ce1d-11e4-9af3-fd70715e5e55.png)
Diese berücksichtigt alle eingegangen Anträge und bietet je nach Status des Antrags die verschiedenen "Editieroptionen". Das ist die Ansicht als Admin, aus meiner Sicht können die Filter ggf. auch die Teilnehmer haben.

**Comment by CatoTH** [comment]
Ich hab es jetzt mal für Status, Schlagworte / TOPs und Titel eingebaut. Weitere Kriterien kann ich bei Bedarf auch noch hinzufügen.

**Comment by joriki** [comment]
Kommentare von Gerhard Lippe <Gerhard.Lippe@gruene.de> per Mail:

> Wichtig (nicht nur für die BDK) ist, dass wir ALLE Anträge (eigenständige und Änderungsanträge) in einer Liste im Backend haben, d.h. auch die Anträge, die nur eingereicht sind.

> Beim Filtern fehlen noch die AntragstellerInnen ("Schlagwort" sollte beim Filtern in "TOP" umgenannt werden). Und wir müssen die Möglichkeiten haben, Aktionen für die gefilterten Anträge durchzuführen, z.B. Löschen, Status ändern etc.

**Comment by joriki** [comment]
Weiterer Email-Kommentar von Gerhard Lippe <Gerhard.Lippe@gruene.de>:

> Ach ja, wir brauchen eine Tabelle bei der BDK ähnlich wie beim Tool von Ressourcenmangel.

s.o. screenshot von grafgraffy -- aus meiner Sicht ist dabei wesentlich, daß die Anträge nur eine Zeile in der Tabelle einnehmen und nicht wie im Moment viel vertikalen Platz pro Antrag, damit man viele auf einmal darstellen und überschauen kann. Ich könnte mich ab nächster Woche darum kümmern.

**Comment by joriki** [comment]
Weiterer Email-Kommentar von <Gerhard.Lippe@gruene.de>

> Bei der Filterung wäre es übersichtlicher, wenn ihr/wir eine Darstellung wie beim RM-Tool hinbekommen könnten. Bei den AntragstellerInnen wäre eine Freitextsuche einfacher als ein Pull-Down-Menü, da es z.B. bei BAGen oft unterschiedliche Schreibweisen gibt BAG Demokratie und Recht bzw. BAG Demokratie & Recht.

**Comment by gerhardlippe** [comment]
Beim RM-Tool gab es keine Unterscheidung zwischen Anträgen und Änderungsanträgen - das müssen wir beibehalten. D.h. die Filterung muss für alle Anträge und Änderungsanträge möglich sein.

**Comment by CatoTH** [comment]
@gerhardlippe ich hatte vor ein paar Tagen eine Liste sowohl mit Anträgen als auch Änderungsanträgen angefangen. Sie wird auf der Admin-Startseite verlinkt, als "Liste aller Anträge und Änderungsanträge". (Die Liste gibt es jetzt auch bei den alten Veranstaltungen, z.B. https://bdk-hh-2014.antragsgruen.de/)

**Comment by gerhardlippe** [comment]
Ja das ist schon klar, das sehe ich auch auf der Startseite. Mir geht es
um das Backend, da sind ja die Anträge und Änderungsanträge noch
getrennt und somit auch nur getrennt zu filtern, bzw. bei den
Änderungsanträgen gibt es noch keine Filtermöglichkeit.



Am 13.04.2015 um 10:25 schrieb Tobias Hößl:
> @gerhardlippe <https://github.com/gerhardlippe> ich hatte vor ein paar
> Tagen eine Liste sowohl mit Anträgen als auch Änderungsanträgen
> angefangen. Sie wird auf der Admin-Startseite verlinkt, als "Liste aller
> Anträge und Änderungsanträge". (Die Liste gibt es jetzt auch bei den
> alten Veranstaltungen, z.B. https://bdk-hh-2014.antragsgruen.de/)
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CatoTH/antragsgruen/issues/38#issuecomment-92267075>.
> 

-- 
Gerhard Lippe
Organisation/Gremien
BÜNDNIS 90/DIE GRÜNEN
Bundesgeschäftsstelle
Platz vor dem Neuen Tor 1
10115 Berlin
Tel.: 030 - 28 442 -128
Fax: 030 - 28 442 -328
Mobil: 01520 - 158 10 54
e-mail: gerhard.lippe@gruene.de
www.gruene.de

**Comment by CatoTH** [comment]
@gerhardlippe Also konkret meine ich diese Seite hier im Backend: https://bdk-hh-2014.antragsgruen.de/BDK-HH-2014/admin/antragsliste
Da gibt es ja schon eine Filtermöglichkeit.

**Comment by gerhardlippe** [comment]
Sorry, das hatte ich übersehen. Ja, das sieht gut aus. Wenn man da jetzt
noch Aktionen durchführen kann, wie Löschen oder Status ändern wäre das
klasse.

Am 13.04.2015 um 10:33 schrieb Tobias Hößl:
> @gerhardlippe <https://github.com/gerhardlippe> Also konkret meine ich
> diese Seite hier im Backend:
> https://bdk-hh-2014.antragsgruen.de/BDK-HH-2014/admin/antragsliste
> Da gibt es ja schon eine Filtermöglichkeit.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CatoTH/antragsgruen/issues/38#issuecomment-92271066>.
> 

-- 
Gerhard Lippe
Organisation/Gremien
BÜNDNIS 90/DIE GRÜNEN
Bundesgeschäftsstelle
Platz vor dem Neuen Tor 1
10115 Berlin
Tel.: 030 - 28 442 -128
Fax: 030 - 28 442 -328
Mobil: 01520 - 158 10 54
e-mail: gerhard.lippe@gruene.de
www.gruene.de

**Comment by CatoTH** [comment]
Ich hab die Aktionen bei einzelnen Anträgen jetzt mit eingebaut (Freischalten bzw. "Ent-Freischalten", Löschen, und Klonen), zusammen mit einer Sortier-Funktion.

**Comment by gerhardlippe** [comment]
Geht das auch bei Änderungsanträgen, vor allem das Klonen wäre wichtig.

Am 19.04.2015 um 15:31 schrieb Tobias Hößl:
> Closed #38 <https://github.com/CatoTH/antragsgruen/issues/38>.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CatoTH/antragsgruen/issues/38#event-284704882>.
> 

-- 
Gerhard Lippe
Organisation/Gremien
BÜNDNIS 90/DIE GRÜNEN
Bundesgeschäftsstelle
Platz vor dem Neuen Tor 1
10115 Berlin
Tel.: 030 - 28 442 -128
Fax: 030 - 28 442 -328
Mobil: 01520 - 158 10 54
e-mail: gerhard.lippe@gruene.de
www.gruene.de

**Comment by CatoTH** [comment]
Ich hab die "Antrag auf dieser Basis"-Funktion jetzt auch für Änderungsanträge eingebaut. Passt das so?
