### ISSUE TITLE
Zuständigkeit

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#39]
Es sollte eine Zuständigkeit für Anträge festlegbar sein (nach der dann auch gefiltert werden kann). Am besten zwei getrennte Felder, einmal allgemeine Zuständigkeit (z.B. in der Antragskommission), einmal, wer grade konkret am Ball ist, also den nächsten Schritt machen müßte, um die Behandlung des Antrags voranzubringen. Sollte aus einer konfigurierbaren Liste aussuchbar sein.

**Comment by CatoTH** [comment]
Ist jetzt (so ähnlich) in der Version 4.4 enthalten.
