### ISSUE TITLE
Tagesordnungspunkte

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#40]
Es sollte möglich sein, TOPs zu definieren, Anträge zu bestimmten TOPs zu stellen und als Admin Anträge anderen TOPs zuzuweisen.

**Comment by CatoTH** [comment]
Das würde ich über die schon bestehende Schlagwortfunktion lösen, ggf. das ganze dann noch in der Anzeige etwas dafür anpassen.
