### ISSUE TITLE
Eigenständige Anträge in Änderungsdarstellung

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#42]
Bei Satzungsänderungen u.ä. ist es wünschenswert, daß die Änderung im Änderungsmodus dargestellt wird, mit Durchstreichen etc., obwohl es sich um einen eigenständigen Antrag und nicht um einen Änderungsantrag handelt. Dazu sollte es möglich sein, den bestehenden Satzungstext o.ä. einzugeben und dann den Antrag so zu stellen und darzustellen, wie Änderungsanträge gestellt und dargestellt werden; der Antrag sollte dennoch als eigenständiger Antrag behandelt werden. Es wäre zu überlegen, wie dann hierzu Änderungsanträge gestellt und dargestellt werden sollten.

**Comment by CatoTH** [comment]
Mit Gerhard hab ich eben darüber gesprochen; als schnelle Ad-Hoc-Lösung für den Länderrat wäre eine Lösung, einfach mal nur Durchgestrichen als Formatierung zuzulasen. Eine ausgefeiltere Lösung ersetzt das nicht, nur ist letztere leider nicht so auf die Schnelle umgesetzt.

**Comment by CatoTH** [comment]
Durchgestrichen ist als Formatierung möglich, ab Version 3 auch standardmäßig. Für die Zukunft wäre noch eine explizite Unterstützung von <ins> und <del> möglich, aber das würde ich mal noch auf eine zukünftige Version verschieben.

**Comment by joriki** [comment]
Warum hast Du das geschlossen? Wollen wir das nicht langfristig immer noch?

**Comment by CatoTH** [comment]
Was genau geht denn noch nicht? Durchstreichen / Unterstreichen geht ja - geht es noch um die grüne/rote Farbe?

**Comment by joriki** [comment]
Vielleicht reicht das in der Praxis -- aber ich fände das hier gut zu haben: "Dazu sollte es möglich sein, den bestehenden Satzungstext o.ä. einzugeben und dann den Antrag so zu stellen und darzustellen, wie Änderungsanträge gestellt und dargestellt werden" -- dann müßte man nicht von Hand bestehende Satzungsteile eingeben und den Kontext dazu beschreiben und durchstreichen etc. (was ein bißchen fehleranfällig ist).

**Comment by CatoTH** [comment]
Satzungsänderungen werden nun explizit mit unterstützt. Der Basis-Text / Die Basis-Texte werden dabei vom Admin eingegeben (beim zugehörigen Antragstypen), Nutzer*innen können dann die Satzungsänderungsanträge wie reguläre Anträge stellen, nur dass es intern eben ÄAs sind, inklusive den zugehörigen Diff-Formatierungen.
