### ISSUE TITLE
AntragstellerInnen in Seitentabs anzeigen

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#43]
In den Tabs am rechten Rand, in denen die Antragsnummern stehen, sollten auch die AntragstellerInnen stehen.

**Comment by CatoTH** [comment]
Also du meinst jetzt auf der Sidebar auf der Startseite?

**Comment by grafgraffy** [comment]
Gemeint ist, wenn man einen Antrag sieht und auf der rechten Seite durch rüberfahren der einzelnen Anträge die Änderungen angezeigt werden, das dann dort der 1. Antragssteller mit dran steht. Entweder man packt das da in den Text des ÄAntrags rein oder man macht das beim Hovereffekt mit unter den Antrag. Keine Ahnung was besser aussieht.

**Comment by joriki** [comment]
Ja, genau, das war gemeint. Wer den Änderungsantrag gestellt hat, ist oft eine wichtige Information, die einem hilft, den Antrag einzuordnen, sich zu erinnern, was darüber schon besprochen wurde u.ä. -- deshalb wäre es gut, wenn das sichtbar wäre, ohne daß man eine neue Seite aufmachen muß (wie zurzeit). Es ist ja genug Platz; ich würde vorschlagen, die (erste) AntragsstellerIn direkt in dem Tab an der Seite anzugeben, z.B. hinter der Antragsnummer in Klammern, damit man nicht erst hovern muß, um es zu sehn -- bei vielen Änderungsanträgen würde das dazu beitragen, schnell einen bestimmten angucken zu können -- ich hab sie meistens eher anhand der AntragstellerIn als anhand der Nummer im Kopf.

**Comment by joriki** [comment]
Die beiden commits oben sind inhaltlich identisch; der erste war auf einem falschen Branch und kann ignoriert werden.
