### ISSUE TITLE
Wunschliste:  Dropdown / Radiobutton Antrags-Abschnitte

### ISSUE THREAD

**Issue by spicywolf00** [CatoTH/antragsgruen#430]
Featurewunsch:

Dropdown/Radiobuttons:
Es wäre cool bei Antragsabschnitten auch Dropdowns auswählbar zu machen:
z.B. kann man bei uns Zuschussanträge stellen: Hier muss man im Antrag allerdings noch den Topf auswählen. Hier wäre ein Dropdown oder/und Radiobuttons ziemlich nützlich.

PS: Super Tool, erleichtert die Arbeit um einiges.

**Comment by CatoTH** [comment]
Lange, lange ist's her... aber im Rahmen der Tabellarischen Angaben ist es nun möglich, Drop-Downs mit vorgegebenen Auswahlmöglichkeiten festzulegen.
