### ISSUE TITLE
Anträge klonen

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#44]
Es sollte möglich sein, einen bestehenden Antrag zu klonen, so dass alle Angaben außer dem Antragstext (AntragstellerInnen, Kontaktdaten, Beschlussdatum, ...) übernommen werden und man direkt auf die Seite gelangt, wo man mit denselben Angaben einen Antragstext bzw. eine Änderung eingeben kann.

**Comment by CatoTH** [comment]
Ich hab das jetzt so wie mit Gerhard besprochen implementiert - also dass die Daten der AntragstellerIn bzw. der UnterstützerInnen übernommen werden, nicht aber Titel und Text der Anträge. Die Funktion befindet sich bei der gesammelten "Anträge + Änderungsanträge"-Liste im Aktionen-Drop-Down rechts.
