### ISSUE TITLE
Verschieben von Bewerbungen/Anträgen

### ISSUE THREAD

**Issue by ymybe** [CatoTH/antragsgruen#441]
Das Verschieben von Anträgen und Bewerbungen sorgte bei mir heute dafür, dass die Bilder aus dem Antrag verschwanden.

Ausserdem wäre es gut den Tagesordnungspunkt beim Verschieben auswählen zu können.

( passiert in tk.antragsgruen.de )

**Comment by CatoTH** [comment]
Hallo,

welche Bilder sind denn genau weg? Bei B1 z.B. seh ich ja schon noch ein Foto - ist das nur kurzzeitig verschwunden, oder geht es um andere Bilder?

**Comment by CatoTH** [comment]
Nochmal hallo,

evtl. hab herausgefunden, was passiert ist. Hattest du beim Verschieben das "Referenz an der alten Stelle behalten" aktiviert? Wenn ja, dürfte der Fehler da gelegen haben. Und dann wäre der Fehler jetzt auch behoben.

**Comment by CatoTH** [comment]
@ymybe Gibst du vielleicht kurz Rückmeldung, ob es jetzt (bei neu verschobenen) Bewerbungen funktioniert? Ansonsten geh ich davon aus, dass das Problem behoben ist.

**Comment by ymybe** [comment]
`Integrity constraint violation (#23000)`

Irgendwie passieren da bei mir komische Sachen. Sorry fuers delay.

**Comment by ymybe** [comment]
Habs jetzt auf der Februarveranstaltung mit referenz in eine neue schieben wollen und es kam dieser fehler.

**Comment by CatoTH** [comment]
Das sollte jetzt auch korrigiert sein. Hier war wohl das Problem, dass der selbe Antrag schon mal zur selben Veranstaltung kopiert wurde und dort dann gelöscht war (aber ein paar Relikte davon noch in der Datenbank lagen und störten - das ist jetzt behoben)
