### ISSUE TITLE
Antragsnummern werden im PDF abgeschnitten

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#45]
Wenn die Antragsnummer eine gewisse Länge überschreitet, wird sie in dem Kästchen oben rechts im PDF nicht mehr bzw. nicht mehr vollständig dargestellt.

**Comment by CatoTH** [comment]
Schickst du mir da kurz mal einen Link auf ein Beispiel?

**Comment by grafgraffy** [comment]
https://bdk-hh-2014.antragsgruen.de/BDK-HH-2014/antrag/1481

Das Problem steckt in protected/components/views/antrag_pdf.php Zeilen 40, 44,45.

Wenn die Buchstabenbreite ungünstig ist (Bspw. ein Antrag mit WWWWW-01) dann klappt die fest definierte Zeichenbreite nicht. Um das Problem zu lösen könnte man entweder die Zeichenbreite höher als 5,5 setzen was dann bei WWWWW-01 super aussieht, bei Antrag IIIIII-02 dann aber ein riesen Rahmen mit zuviel Platz lässt oder man verzichtet ganz auf das Konstrukt. Dann nimmt man bei MultiCell bei der Breite 0. 
Dann hat man aber ein Rahmen so breit wie die Seite. In dem Fall sollte man mehr Informationen unterbringen (spielt in Issue #45 mit rein). 
Ganz Alternativ ware ein Funktion zu schreiben die "weiß" wie breit jedes Zeichen ist und die Breite darüber zu bestimmen. Wehe jemand wechselt die Schriftart.^^
