### ISSUE TITLE
Falscher User beim Kommentieren

### ISSUE THREAD

**Issue by peduso** [CatoTH/antragsgruen#464]
Nach dem Login möchte ich einen Antrag kommentieren. Beim klicken auf die Kommentarfahne wird ein  User angezeigt, mit dem ich nicht angemeldet bin. 

Wenn ich dennoch kommentiere und absende, kommt einer Fehlermeldung. Der Kommentar wird nicht eingetragen. 

Ist das ein Bug oder haben wir das System falsch konfiguriert

?![Antragsgrün Kommentar](https://user-images.githubusercontent.com/2013114/77302714-07fb0c00-6cf2-11ea-911a-03342ca7d1a2.jpg)
![Antragsgruen Kommentar-Fehlermeldung__](https://user-images.githubusercontent.com/2013114/77302769-2103bd00-6cf2-11ea-9f3b-eb94c3a6d64c.png)

**Comment by CatoTH** [comment]
Hallo,

welche Version setzt du denn ein? (Das müsste ganz unten auf der Seite stehen)

Grüße,
  Tobias

**Comment by peduso** [comment]
ah, sorry, 

Antragsgrün, Version 4.3.1

**Comment by CatoTH** [comment]
Ich hab eben entdeckt, dass der Fehler zwar schon seit einem Monat behoben ist, aber die Version noch nicht offiziell veröffentlicht war. Ich hab das jetzt nachgeholt. Ab Version 4.5.1 sollte der Fehler behoben sein. Sprich es gibt zwei Möglichkeiten:
- Das Antragsgrün bei euch auf 4.5.1 aktualisieren (über den Web-Updater in den Einstellungen - das sollte so max. 5-10 Minuten dauern)
- Wenn man es nicht aktualisieren kann, dann hilft leider nur, die Kommentare nicht Pro-Absatz zu einzustellen, denn der Fehler tritt dann auf, wenn man die Kommentare pro Absatz und nicht für den gesamten Antrag einstellt.

**Comment by peduso** [comment]
Auf die aktuelle Version upzudaten hätte ich auch selbst drauf kommen können. 

Ich habe die Updates jetzt gefahren.

Fehler ist behoben.

Danke für die schnelle Rückmeldung.
