### ISSUE TITLE
effizientere Platznutzung im PDF

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#47]
Im PDF wird, insbesondere am oberen Rand, viel Platz auf dem Blatt nicht genutzt; für die Papierverschickung wäre ein platzsparenderes Format wünschenswert.

**Comment by CatoTH** [comment]
Schickst du mir vielleicht einfach mal ein Mockup wie es aussehen soll? Das aktuelle Format war einfach nur eine 1:1-Kopie von den Aussendungen auf der bayerischen LDK.

**Comment by grafgraffy** [comment]
Wie wäre es wenn man das an das Format vom Bundesverband mit anpasst, bspw. so:
https://antragstool.gruene.de/events/17/proposals/4894.pdf
Ggf. was für ein Technikertreffen wo man sich auf ein Format einigt *hüst*.

**Comment by gerhardlippe** [comment]
Wichtig wäre noch, dass ab Seite 2 die Antragsnummer und der Gegenstand erscheint - entweder in der Fuß- oder in einer noch einzurichtenden Kopfzeile

**Comment by gerhardlippe** [comment]
Wichtig wäre noch, dass ab Seite 2 die Antragsnummer und der Gegenstand erscheint - entweder in der Fuß- oder in einer noch einzurichtenden Kopfzeile

**Comment by CatoTH** [comment]
Ist inzwischen umgesetzt.

**Comment by gerhardlippe** [comment]
Hallo Tobias,

bei den pdfs fehlt momentan oben die Veranstaltung und teilweise laufen
sie rechts über das Blatt hinaus (z.B. U-04).

Schöne Grüße

Gerhard

P.S. Wann kommst Du am Donnerstag


Am 18.07.2015 um 13:12 schrieb Tobias Hößl:
> Ist inzwischen umgesetzt.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CatoTH/antragsgruen/issues/47#issuecomment-122530697>.
> 

-- 
Gerhard Lippe
Organisation/Gremien
BÜNDNIS 90/DIE GRÜNEN
Bundesgeschäftsstelle
Platz vor dem Neuen Tor 1
10115 Berlin
Tel.: 030 - 28 442 -128
Fax: 030 - 28 442 -328
Mobil: 01520 - 158 10 54
e-mail: gerhard.lippe@gruene.de
www.gruene.de

**Comment by CatoTH** [comment]
Hi,

Ok, das mit dem PDF schau ich mir noch an. Wäre 10 Uhr am Donnerstag ok?

Grüße,
  Tobias 

----- Ursprüngliche Nachricht -----
Von: "gerhardlippe" <notifications@github.com>
Gesendet: ‎20.‎07.‎2015 10:06
An: "CatoTH/antragsgruen" <antragsgruen@noreply.github.com>
Cc: "Tobias Hößl" <tobias@hoessl.eu>
Betreff: Re: [antragsgruen] effizientere Platznutzung im PDF (#47)

Hallo Tobias,

bei den pdfs fehlt momentan oben die Veranstaltung und teilweise laufen
sie rechts über das Blatt hinaus (z.B. U-04).

Schöne Grüße

Gerhard

P.S. Wann kommst Du am Donnerstag


Am 18.07.2015 um 13:12 schrieb Tobias Hößl:
> Ist inzwischen umgesetzt.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CatoTH/antragsgruen/issues/47#issuecomment-122530697>.
> 

-- 
Gerhard Lippe
Organisation/Gremien
BÜNDNIS 90/DIE GRÜNEN
Bundesgeschäftsstelle
Platz vor dem Neuen Tor 1
10115 Berlin
Tel.: 030 - 28 442 -128
Fax: 030 - 28 442 -328
Mobil: 01520 - 158 10 54
e-mail: gerhard.lippe@gruene.de
www.gruene.de

**Comment by gerhardlippe** [comment]
10 Uhr ist o.k. - wenn du früher möchtest, ist das auch in ordnung, ich
bin ab 8 uhr hier.

gruss
gerhard

Am 20.07.2015 um 10:59 schrieb Tobias Hößl:
> Hi,
> 
> Ok, das mit dem PDF schau ich mir noch an. Wäre 10 Uhr am Donnerstag ok?
> 
> Grüße,
> Tobias
> 
> ----- Ursprüngliche Nachricht -----
> Von: "gerhardlippe" <notifications@github.com>
> Gesendet: ‎20.‎07.‎2015 10:06
> An: "CatoTH/antragsgruen" <antragsgruen@noreply.github.com>
> Cc: "Tobias Hößl" <tobias@hoessl.eu>
> Betreff: Re: [antragsgruen] effizientere Platznutzung im PDF (#47)
> 
> Hallo Tobias,
> 
> bei den pdfs fehlt momentan oben die Veranstaltung und teilweise laufen
> sie rechts über das Blatt hinaus (z.B. U-04).
> 
> Schöne Grüße
> 
> Gerhard
> 
> P.S. Wann kommst Du am Donnerstag
> 
> 
> Am 18.07.2015 um 13:12 schrieb Tobias Hößl:
>> Ist inzwischen umgesetzt.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CatoTH/antragsgruen/issues/47#issuecomment-122530697>.
>>
> 
> -- 
> Gerhard Lippe
> Organisation/Gremien
> BÜNDNIS 90/DIE GRÜNEN
> Bundesgeschäftsstelle
> Platz vor dem Neuen Tor 1
> 10115 Berlin
> Tel.: 030 - 28 442 -128
> Fax: 030 - 28 442 -328
> Mobil: 01520 - 158 10 54
> e-mail: gerhard.lippe@gruene.de
> www.gruene.de
> 
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CatoTH/antragsgruen/issues/47#issuecomment-122816822>.
> 

-- 
Gerhard Lippe
Organisation/Gremien
BÜNDNIS 90/DIE GRÜNEN
Bundesgeschäftsstelle
Platz vor dem Neuen Tor 1
10115 Berlin
Tel.: 030 - 28 442 -128
Fax: 030 - 28 442 -328
Mobil: 01520 - 158 10 54
e-mail: gerhard.lippe@gruene.de
www.gruene.de
