### ISSUE TITLE
Änderungen effizienter und übersichtlicher darstellen

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#48]
Oft wird bei Änderungen mehr umgebener Text dargestellt, als nötig oder sinnvoll.

**Comment by CatoTH** [comment]
Ich befürchte, das erfordert einen tieferen Eingriff in den Diff-Algorithmus. Da der bei v2 noch von Horde stammt, kann ich da nur schwer was ändern. Bei v3 gibt es eine eigene Diff-Implemntierung, da sollte das einfacher möglich sein.

**Comment by CatoTH** [comment]
@joriki könntest du mir da mal zwei, drei Beispiele schicken? Dann überführe ich die mal als Testfälle für die neue Version, um das da dann (hoffentlich) verbessern zu können.

**Comment by CatoTH** [comment]
Notiz: Ein Änderungsantrag, wo es solche Probleme gibt, wäre: https://1laenderrat2015.antragsgruen.de/1Laenderrat2015/antrag/1773/aenderungsantrag/6009
