### ISSUE TITLE
Support SVG as logo file

### ISSUE THREAD

**Issue by macwinnie** [CatoTH/antragsgruen#489]
Hi @CatoTH =)

es wäre großartig, wenn eine der nächsten Versionen den Upload von SVG-Dateien als Seiten-Logo unterstützen könnte.

Beste Grüße,
Martin

**Comment by CatoTH** [comment]
Hi!

Ich schau, dass ich das in den nächsten 1-2 Wochen in der nächsten Version mit reinbringe. :)

Grüße,
  Tobias
