### ISSUE TITLE
Bug in protected/views/layouts/bootstrap.php Zeile 101

### ISSUE THREAD

**Issue by grafgraffy** [CatoTH/antragsgruen#50]
Dort heisst es:
<? } ?>
Kontext:
...
<li><a href="<?= CHtml::encode($this->createUrl("admin/index")) ?>">Admin</a></li>
<?php } ?>
</ul>
<? } ?>
</div>
</div>
...
Leider fehlt da das php und es müsste so heißen wie zwei Zeilen darüber. Des weiteren Frage ich mich ob <?= CHtml (erste Zeile) auch so okay ist, habs jetzt bei meiner Installation, auch in dieser Datei, an 4 Stellen pro Forma geändert.

**Comment by CatoTH** [comment]
Sollte mit https://github.com/CatoTH/antragsgruen/commit/13fd780479ad8b881ce3527a69939b9f7ce92091 behoben sein (also dass es jetzt ein <?php ist - ich hoffe mal, das war das Gemeinte).

**Comment by grafgraffy** [comment]
Ja das war gemeint, k.A. warum der das hier abgkürzt hat. Mittlerweile habe ich auch short_tags an nachdem ich gesehen habe das in meiner php.ini das zwei mal drin stand (am ende natürlich aus).
