### ISSUE TITLE
Support (Start)TLS SMTP encryption in UI

### ISSUE THREAD

**Issue by lukas-staab** [CatoTH/antragsgruen#501]
in `config/config.json` 
```
... 
"mailService": {
        "transport": "smtp",
        "host": "XXX",
        "port": "587",
        "authType": "plain",
        "username": "XXX",
        "password": "XXX",
        "encryption" : "tls"
    }
```
encryption tag is needed if (start)tls is needed - UI does not support this setting in last realese  4.6.1 so far

**Comment by CatoTH** [comment]
Hi,
the new version 4.6.2 provides a checkbox to enable TLS. I hope this works for you :)
