### ISSUE TITLE
Enhancement html/infos/impressum ins Repository

### ISSUE THREAD

**Issue by grafgraffy** [CatoTH/antragsgruen#51]
Der Impressum Link zeigt auf html/infos/impressum, dort gibts weder eine "default" seite noch exisitiert der Ordner. Wäre gut wenigstens ein Grundgerüst dort zu haben.

**Comment by grafgraffy** [comment]
Das betrifft auch die Verlinkung auf html/infos/selbstEinsetzen.

**Comment by CatoTH** [comment]
Es sind alle HTML-Seiten rein virtuelle Seiten, die nicht als Datei im Repository liegen, sondern dynamisch aus der Datenbank generiert werden. Wenn da ein 404 Not Found oder ähnlich kommt, ist vermutlich der Webserver noch nicht so konfiguriert, dass die Seiten über die index.php aufgelöst werden. Wie das genau geht, hängt etwas vom Webserver ab. Für nginx ist eine Beispiel-Konfig in docs/, bei Apache macht das die html/.htaccess-Datei automatisch - wenn das in der Haupt-Apache-Konfig erlaubt ist (AllowOverride oder so ähnlich)

**Comment by grafgraffy** [comment]
Danke für den Tipp, da kommt dann dennoch:
The requested URL /index.php/infos/selbstEinsetzen was not found on this server.

**Comment by CatoTH** [comment]
Mit welchem Webserver denn?

**Comment by grafgraffy** [comment]
Apache, aber ich sehe gerade in den Logs 
script '/var/www/html/index.php' not found or unable to stat
er sollte aber eigentlich auf  /var/www/html/antragsgruen/html/index.php zugreifen. Ähnliches Problem wie mit den Logos. Ich kucke mal was ich da machen kann.

**Comment by CatoTH** [comment]
Klingt jetzt tatsächlich eher nach einem falsch gesetzten DocumentRoot oder etwas ähnlichem...

**Comment by grafgraffy** [comment]
Okay ich hab in der .htaccess die RewriteBase angepasst für mein Verzeichnis (hab keinen vhost) jetzt laufen die meisten Seiten. Vielleicht kann das in die "Install" Doku aufgenommen werden oder aber die empfehlung einen vhost zu nehmen.
