### ISSUE TITLE
Änderungsanträge im status "Zurückgezogen" und "Abgelehnt" werden weiter in Übersicht angezeigt

### ISSUE THREAD

**Issue by NordmeyerT** [CatoTH/antragsgruen#511]
Wenn ich einen ÄA unter Admin:bearbeiten von "Eingereicht" auf "Abgelehnt" oder "Zurückgezogen" stelle, bleibt er weiter in der Übersicht sichtbar. Ich würde erwarten, dass ÄA in den neuen Zuständen dort verschwinden. Einige, die diesen Statuswechsel erlebt haben, sind auch weg. 

Wie kriege ich die anderen auch aus der Übersicht?

**Comment by CatoTH** [comment]
Soweit ich weiß, sind zurückgezogene Anträge momentan noch immer sichtbar - mich wundert da gerade eher, dass du sagst, dass einige verschwunden sind...? Es stimmt schon, dass man da auch argumentieren kann, dass die besser verschwinden sollten - ich hatte auch schon mal überlegt, das als Einstellungsmöglichkeit einzubauen - bislang aber glaube ich noch nicht...
