### ISSUE TITLE
Enhancment in protected/views/layouts/bootstrap.php Pfadangaben für Icons

### ISSUE THREAD

**Issue by grafgraffy** [CatoTH/antragsgruen#52]
In besagter Datei sind die Links auf die Icons, hier exemplarisch
&lt;link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196"&gt;
so gesetzt das er im "Wurzelverzeichnis" sucht. Der Ordnerstruktur entnehme ich aber wenn ich das in ein Unterverzeichnis packe bspw. example.com/antragsgruen dann sucht er die Icons in example.com statt in example.com/antragsgruen/html.
Mein Vorschlag entweder in:
&lt;link rel="icon" type="image/png" href="html/favicon-196x196.png" sizes="196x196"&gt; oder
&lt;link rel="icon" type="image/png" href="favicon-196x196.png" sizes="196x196"&gt; oder ganz neu in 
&lt;link rel="icon" type="image/png" href="/img/favicon-196x196.png" sizes="196x196"&gt; ändern und die Bilder entsprechend auslagern.

**Comment by CatoTH** [comment]
Vermutlich wäre das sinnvollste, ein &lt;base&gt;-Tag im HTML-Header?
Zugegebenermaßen hatte ich den Fall, dass man Antragsgrün in ein Unterverzeichnis installiert, tatsächlich noch nicht mit bedacht...

(Meta-Diskussion: Wie man bei Github-Kommentaren das Problem mit den HTML-Tags am einfachsten löst, weiß ich jetzt auch grad nicht auswendig; ich benutze dann immer die HTML-Entities dafür, also &amp;lt; und &amp;gt; statt &lt; und &gt;)

**Comment by grafgraffy** [comment]
Das mit dem Unterverzeichnis mach ich grad und stoße dann doch an das ein oder andere Problemchen. Aber man wächst ja mit den Aufgaben. :) Hab jetzt die Spitzen Klammern "überarbeitet".
