### ISSUE TITLE
Grünes CA uses deprecated LaTex Package which is now removed

### ISSUE THREAD

**Issue by lukas-staab** [CatoTH/antragsgruen#524]
See https://komascript.de/faq_scrpage2_en for reference - I exchanged the Package in the grünes CI database as proposed in the link. It seems like the package scrpage2 is no longer in the Fedora Repositorys and was removed with the last (?) update.

Antragsgruen throws the following error, after the package change (path redacted)
``
Error: app\models\exceptions\Internal: An error occurred while creating the PDF: PATH=/usr/ TEXMFCACHE='[...]/runtime/tmp/' /usr/bin/lualatex -output-directory='[...]/runtime/tmp/' '[...]/runtime/tmp/motion-pdf5fb0ed1ccef0a.tex' in [...]/components/latex/Exporter.php:572 Stack trace: #0 [...]/views/motion/pdf_collection_tex.php(28): app\components\latex\Exporter->createPDF() #1 [...]/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/lako.j...') #2 [...]/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile() #3 [...]/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile() #4 [...]/vendor/yiisoft/yii2/base/Controller.php(440): yii\base\View->render() #5 [...]controllers/MotionExportTraits.php(257): yii\base\Controller->renderPartial() #6 [internal function]: app\controllers\MotionController->actionPdfcollection() #7 [...]/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #8 [...]/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams() #9 [...]/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction() #10 [...]/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction() #11 [...]/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest() #12 [...]/web/index.php(22): yii\base\Application->run() #13 {main}
``

The weird thing is if i execute: `lualatex motion-pdf5fb0ed1ccef0a.tex` in `/runtime/tmp` by hand there is no error, quite some warnings, but no error. Therefore I am not sure how to further debug this issue, due to i cannot find the orinal latex .log file from the application.

**Comment by CatoTH** [comment]
I had this issue too a short while ago and haven't really investigated the different versions yet. But the following SQL statement helped me: `UPDATE texTemplate SET texLayout = REPLACE(texLayout, 'scrpage2', 'scrlayer-scrpage');` (this replaces the module by the new one). Maybe this helps in your case, too?

**Comment by lukas-staab** [comment]
I did this already before issuing - did not change the output :( 
Is there any latex .log file produced from antragsgruen? Then I could debug the latex myself.
