### ISSUE TITLE
Enhancement protected/config/main.php

### ISSUE THREAD

**Issue by grafgraffy** [CatoTH/antragsgruen#53]
Ich schlage vor in die Default Konfiguration die Funktion 
date_default_timezone_set('Europe/Berlin'); 
mit aufzunehmen damit alle Datumsfunktionen für das Projekt das verwenden. 
Sonst gibts bei den neueren PHP Versionen die Warnung:
date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Berlin' for 'CET/1,0/no DST' instead

**Comment by joriki** [comment]
Ich hatte dasselbe Problem -- hatte es bei mir dadurch gelöst, daß ich in `/etc/php.ini` eine Zeile `date.timezone = Europe/Berlin` eingefügt hab, aber die Lösung über die Default-Konfiguration ist vielleicht besser, weil sie keinen zusätzlichen Installationsschritt erfordert.
