### ISSUE TITLE
Mandanten oder Untergliederungen im System die Nutzung ermöglichen

### ISSUE THREAD

**Issue by peduso** [CatoTH/antragsgruen#533]
Hallo,

ist es geplant eine Instanz nutzbar zu machen, die es auch Untergliederungen eines Verbandes erlaubt dort ihre Anträge zu Administrieren?

Vorteil: Personen die auf mehreren Ebenen unterwegs sind, kommen mit einem Login aus und können dor jeweils aktiv werden.

Voraussetzungen: Funktionen und Administration von Veranstaltungen und Events müssten auf Untergliederungen verteilt werden.

Konkretes Beispiel: Der Admin der Bundesebene kann Veranstaltungen anlegen und Adminisitrieren. Zusätzlich kann er Untergliederungen Anlegen. Jede Untergliederung bekommt einen Admin der wiederum Veranstaltungen anlegen und administrieren kann. 

Eine dritte und vierte Ebene wären noch denkbar.

Ist das ein denkbares Szenario oder zu komplex und doch besser durch Einzelinstanzen abzubilden?

**Comment by CatoTH** [comment]
Hallo,

ich befürchte eher, dass hier die Einzelheiten zu sehr von der jeweiligen Organisation abhängig sind, als dass eine Lösung für alle hier passen würde. Im grundlegenden Datenmodell gibt es das schon - auf der Seite für die Grünen hab ich das unter https://antragsgruen.de/ ja z.B. schon so ähnlich umgesetzt, da dann aber mit der Maßgabe, dass das ganze an ein spezielles SSO-System angebunden wird, in dem die Rechte verwaltet werden. Insofern sehe ich da den Weg eher weiterhin darin, das "Standard-Antragsgrün" einfach mit nur einer Seite zu behalten (die verschiedene Unterveranstaltungen haben kann), und die Mandantenfähigkeit dann im Einzelfall kundenspezifisch zu entwickeln. (Das Plugin, das die Funktionalität auf https://antragsgruen.de abbildet, befindet sich z.B. unter https://github.com/CatoTH/antragsgruen/tree/main/plugins/antragsgruen_sites , das von https://discuss.green unter https://github.com/CatoTH/antragsgruen/tree/main/plugins/green_manager )

**Comment by peduso** [comment]
Danke für die Antwort und den Hinweis.  Wir werden mal schauen, ob das mit plugin und SSO etwas für uns ist.
