### ISSUE TITLE
Textarea unter Selbstvorstellungen (bei Bewerbung einreichen) nicht clickbar bzw. hidden

### ISSUE THREAD

**Issue by PtrAmbs** [CatoTH/antragsgruen#570]
Moin!

Ich versuche gerade Antragsgrün für unseren Juso LV zu implementieren, und dabei ist mir aufgefallen, dass beim einreichen einer Bewerbung die eigentliche text-area hidden (css `display: none`) ist und nur eine unanwählbare div statt des Textfeldes angezeigt wird. Ich habe schon mit einem Genossen versucht das Problem zu troubleshooten, aber da wir uns beide nicht so gut mit yii auskennen haben wir bei der Seitenkonstruktion nicht ganz durchgeblickt.

Danke, dass ihr das ganze open-source zur Verfügung stellt!

Solidarische Grüße,
Peter

![Screenshot 2021-04-16 ant](https://user-images.githubusercontent.com/82176815/115052059-c8472980-9edd-11eb-83eb-c62966f3985d.png)

**Comment by CatoTH** [comment]
Hallo,
das klingt sehr danach, dass da irgendwas mit dem JavaScript nicht richtig geladen werden konnte. Die relevante Ausgabe wäre da vermutlich eher die "Console" oder das "Network" in der Debug-Leiste unten. Insbesondere ob bei Network irgendwelche JS-Bibliotheken nicht geladen wurden.
Habt ihr das denn über vorgefertigte ZIP installiert, oder über Git, bzw. über Kommandozeile mit npm & co?

**Comment by PtrAmbs** [comment]
Moin!
Danke, das war das Problem. Da ich Antragsgrün zu testzwecken erstmal via Git auf einem xampp-Server auf Windows installiert, daher war das mit npm schwierig 🙈 Ein schneller Blick in die Console/Network-Pane haben gezeigt dass moment.js nicht geladen wurde, habe das händich nachgeladen und es funktioniert einwandfrei. Absolut mein Fehler, danke nochmal für die Hilfe!
