### ISSUE TITLE
fehlerhafte Antragsdarstellung in Android

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#59]
Anträge werden auf meinem Phone (Android 4.2.2, Kernel 3.4.5, Build W20-HL.V0026) falsch dargestellt.

 Im Querformat sind die Zeilenummern (außer der ersten jedes Absatzes) falsch positioniert: 

![screenshot_2015-03-25-10-13-37](https://cloud.githubusercontent.com/assets/1418717/6821563/316eb370-d2d8-11e4-8b6a-ddb859b83bff.png)

Im Hochformat erscheinen gar keine Zeilennummern:

![screenshot_2015-03-25-10-13-50](https://cloud.githubusercontent.com/assets/1418717/6821562/31383660-d2d8-11e4-8711-a98b55572101.png)

**Comment by CatoTH** [comment]
Die Zeilennummern sollten hier gar nicht angezeigt werden, da die festen Zeilenumbrüche bei so kleinen Zeilen ja auch weg sind (ansonsten würde das den Lesefluss IMHO stärker beeinträchtigen als die Zeilennummern hier noch helfen).

**Comment by joriki** [comment]
Sieht jetzt gut aus.
