### ISSUE TITLE
Anträge durchsuchen führt zu Fehlermeldung

### ISSUE THREAD

**Issue by joriki** [CatoTH/antragsgruen#60]
Wenn ich in der Admin-Antragsliste rechts unter "Aktionen" auf "Durchsuchen" klicke, bekomme ich die Fehlermeldung `Weder Antrag noch zugehörige Behavior haben einen Scope "search".`

**Comment by CatoTH** [comment]
Das war ein Überbleibsel von einem automatischen Codegenerator (giix); das Durchsuchen-Modul war leider ziemlich unbrauchbar, daher hatte ich es irgendwann entfernt und hier nur vergessen den Link zu entfernen.
