### ISSUE TITLE
###ZEILENNUMMER### angezeigt bei Anträgen, die Text ohne Zeilennummerierung haben

### ISSUE THREAD

**Issue by prggz** [CatoTH/antragsgruen#611]
Bei Anträgen die einen Abschnitt ohne Zeilennummerierung aber mit Typ Text haben, wird bei der Webdarstellung vor jeder Zeile ###ZEILENNUMMER### ausgegeben. Im PDF ist die Darstellung ok.

Zeilennummerierung anzuschalten ist keine Option, da dann die Nummerierung global über alle Abschnitte erfolgt.

![Screenshot (39)](https://user-images.githubusercontent.com/8375100/141474245-5205bd89-4173-4085-98d9-e81f713c2785.png)
![Screenshot (40)](https://user-images.githubusercontent.com/8375100/141474250-e924fde3-ef0a-46fe-b00a-f843053aa85e.png)

**Comment by CatoTH** [comment]
Hallo,
ich schaue mir das morgen (Samstag) an, ich hoffe, das reicht.

**Comment by prggz** [comment]
Aber klar! :)

**Comment by CatoTH** [comment]
Es sollte jetzt wieder passen.
