### ISSUE TITLE
Hinzufügen von Benutzerinnen teilweise defekt

### ISSUE THREAD

**Issue by b90g** [CatoTH/antragsgruen#616]
Auf admin/siteaccess lassen sich Anwenderinn aus dem grünen Netz immer nur einzeln hinzufügen. Bei einem Test mit einer Liste aus 7 Personen wurde nur die letzte Person hinzugefügt für alle anderen gab es Fehlermeldungen. Keine Leerzeichen am Ende der Zeile, pro Zeile ein Accountname.

Dieses Feld ist gemein:

![Screenshot 2022-01-12 at 13-02-20 Zugang zur Veranstaltung (Antragsgrün)](https://user-images.githubusercontent.com/63392812/149136923-1a855f51-ac06-4291-abd3-ef330b30c3de.png)

**Comment by CatoTH** [comment]
@b90g Falls es nicht dringend ist, würde ich das mit der nächsten Version beheben, die späten Februar wohl auf *.antragsgruen.de online gehen wird. Denn die User-Verwaltung wird da eh komplett umgestellt (siehe https://github.com/CatoTH/antragsgruen/pull/615)

**Comment by b90g** [comment]
Keine Eile, ist mir nur beim Support aufgefallen. Ich guck mir das Update an, klingt interessant, danke.

**Comment by CatoTH** [comment]
Sollte inzwischen behoben sein.
