### ISSUE TITLE
Abstimmungen können nicht gelöscht werden

### ISSUE THREAD

**Issue by simonschwarzmueller** [CatoTH/antragsgruen#618]
Auszug aus der Hilfe-Seite: _Genauere Einstellungen zum Abstimmungblock sowie die Möglichkeit ihn wieder zu löschen finden sich, wenn man neben dem Titel des Blocks auf das Einstellungs-Icon klickt._

Allerdings wird das Einstellungs-Icon nicht angezeigt.

![image](https://user-images.githubusercontent.com/30432637/150392235-cc4455a0-85eb-424b-b6b2-546cfa43b4d6.png)

**Comment by CatoTH** [comment]
Das ganze wirkt für mich etwas so, als wäre da etwas mit den Stylesheets schief gegangen. Ist das eine selbst gehostete Instanz? Falls ja, wie ist denn der genaue Link?

**Comment by simonschwarzmueller** [comment]
Ja, es handelt sich um eine selbst gehostete Instanz: https://antragsgruen.kjg.de/

**Comment by simonschwarzmueller** [comment]
![Unbenannt](https://user-images.githubusercontent.com/30432637/150397261-7733769a-0d73-4453-825f-42bff977c35d.png)

Danke für den Hinweis. Das Einstellungsrad hatte die gleiche Farbe wie der Hintergrund. Beim Drüberfahren mit dem Mauszeiger wird es sichtbar.

**Comment by CatoTH** [comment]
Es schaut für mich so aus, als wären die nötigen Layout-Änderungen fürs Voting noch nicht mit aktiv. In dem Screenshot oben schaut nämlich einiges etwas kaputt aus.
Versuch vielleicht mal folgendes: Bei den Einstellungen unter Aussehen habt ihr ja das Farbschema angepasst, wenn ich das richtig sehen. Ändere da vielleicht einmal einen kleinen Wert minimal und speichere. Vielleicht funktioniert es dann ja richtig bzw. schaut richtiger aus? Danach kann man ggf. auch wieder zurückstellen, Hauptsache die Styles werden einmal neu erzeugt.

**Comment by simonschwarzmueller** [comment]
Ich habe einen Farbwert minimal verändert, jetzt wird es korrekt angezeigt. Wenn ich allerdings den alten Wert wieder zurücksetze, ist das Aussehen allerdings wieder wie vorher.

Vorher:

![image](https://user-images.githubusercontent.com/30432637/150400775-8f2c7c1a-a550-443d-86df-449d99653d37.png)

Nachher:

![image](https://user-images.githubusercontent.com/30432637/150400783-eec8e495-af92-4a16-8af0-2419f13bd217.png)

**Comment by CatoTH** [comment]
Also einmal würde ich sicherstellen, dass der Browsercache geleert wird. Wenn das nicht hilft, hilft evtll eine der beiden Punkte hier:
- in der Datenbank in consultationFile eine Datei mit dem Namen style.css suchen, und da den Eintrag löschen. Und falls das nichts hilft,
- auf der Konsole einmal `./yii cache/flush-all` ausführen.
