### ISSUE TITLE
Translation to English

### ISSUE THREAD

**Issue by honikos** [CatoTH/antragsgruen#626]
Part "Consultation"

Nur direkte Antworten auf meine Kommentare 
noti_comments_replies
Only direct answers to my comments

Zu Anträgen, die ich gestellt / kommentiert habe
noti_comments_motions
Motions I commented on

Alle Kommentare in dieser Veranstaltung
noti_comments_con
Comments in all motions

**Comment by CatoTH** [comment]
Hi!

Thank you! I added these translations and they will be part of the next release.
