### ISSUE TITLE
AntragstellerInnen nachträglich ändern

### ISSUE THREAD

**Issue by gerhardlippe** [CatoTH/antragsgruen#64]
Wenn ich die AntragstellerInnen nachträglich ändern will, habe ich nicht die Möglichkeit bei den Gremien das Beschlussdatum bzw. bei einzelnen AntragstellerInnen den KV einzutragen.

**Comment by CatoTH** [comment]
Ich hab das Formular im Backend jetzt leicht überarbeitet. Es gibt jetzt Textfelder für die Organisation und das Beschlussdatum. Dafür hab ich das Auswahlfeld mit den existierenden Personen entfernt, da das ewig lang wurde - und soweit ich das überblicken kann auch nicht verwendet wird, oder irre ich mich da?

**Comment by CatoTH** [comment]
Das sollte durch den neuen Bearbeitungs-Modus inzwischen möglich sein.
