### ISSUE TITLE
Verschieben von Anträgen übernimmt nur Text

### ISSUE THREAD

**Issue by prggz** [CatoTH/antragsgruen#648]
Hallo,

Ich muss für eine Veranstaltung Bewerbungen aus einer Veranstaltung in eine andere verschieben. Dabei werden andere Felder als der Haupt-"antrags"-text anscheinend nicht übernommen. Zumindest keine Bilder und PDF Uploads.

Könnt ihr dies anpassen? Vielen Dank!

**Comment by CatoTH** [comment]
Hallo,

wie dringend ist es? Ich würde vss. am Donnerstag dazu kommen, falls das reicht?

**Comment by prggz** [comment]
Hallo,

das reicht auf jeden Fall! Wenn ich das nächste Woche Mittwoch machen kann, reicht es denke ich! Freitag wäre genial.

Vielen Dank!







---- On Mon, 23 May 2022 18:03:33 +0200 Tobias Hößl ***@***.***> wrote ----





Hallo,

wie dringend ist es? Ich würde vss. am Donnerstag dazu kommen, falls das reicht?

**Comment by CatoTH** [comment]
Ich hoffe, dass es jetzt funktioniert. Kannst du es einmal ausprobieren und mir dann Feedback geben, ob es geklappt hat?

**Comment by prggz** [comment]
Sieht gut aus und klappt. Kannst von mir aus schließen als resolved.
