### ISSUE TITLE
OpenOffice Calc Export

### ISSUE THREAD

**Issue by CatoTH** [CatoTH/antragsgruen#67]
An allen Stellen, an denen es bislang Excel-Exports gab, soll es auch bzw. stattdessen einen Export im Open-Document-Format (konkret: ODS) geben.

**Comment by CatoTH** [comment]
Wunsch Gerhard [20.04.2015]: Flexible Spaltenbreite

**Comment by akuckartz** [comment]
Es geht hier vermutlich weniger um OpenOffice.org oder LibreOffice als um die offenen Open Document Formate (ODF), konkret: um OpenDocument-Tabellendokumente (ODS, "S" für "Spreadsheet").

**Comment by CatoTH** [comment]
@akuckartz Ja stimmt natürlich, das war nur so informell dahingeschrieben. Hab es nochmal etwas konkretiesiert. :)
