### ISSUE TITLE
Outdated browserslist

### ISSUE THREAD

**Issue by Rotzbua** [CatoTH/antragsgruen#675]
## Problem

The `browserslist` seems very outdated and incompatible to the used vue version 3.

Vue requires native `ES2015` support. For this reason old dead IE is not supported and do not need to be listed anymore.
Source: https://vuejs.org/about/faq.html#what-browsers-does-vue-support

## Affected code

https://github.com/CatoTH/antragsgruen/blob/main/package.json

```json
  "browserslist": [
        ">1%",
        "last 10 versions",
        "IE 9",
        "Firefox 3"
    ]
```

## Possible solution

Use the default values of `browserslist`:

```json
  "browserslist": [
        ">0.5%",
        "last 2 versions",
        "Firefox ESR",
        "not dead"
    ]
```

Source:
https://github.com/browserslist/browserslist

## Effect

The processed files should be smaller and faster at loading due less overhead.

**Comment by CatoTH** [comment]
Ok, yes, fair point. While the setting doesn't have any effect on Vue, as it's only used for CSS postprocessing, the combined CSS file did indeed shrink by 12%.
