### ISSUE TITLE
Version-Tag Naming-Convention Change?

### ISSUE THREAD

**Issue by macwinnie** [CatoTH/antragsgruen#683]
Hi @CatoTH =)

On the [Docker-Project by Jugendpresse Deutschland e.V.](https://github.com/jugendpresse/docker-antragsgruen/blob/master/.github/workflows/main.yml#L52) we rely on the semantic naming of the versions with `v` prefix (so `v<major>.<minor>.<patch>`.

Is the release naming done manually so the [newest `4.10.1` tag](https://github.com/CatoTH/antragsgruen/releases/tag/4.10.1) was named by accident without the prefix or is it a general change of the tag naming?

Thanks a lot!
Best
@macwinnie

**Comment by macwinnie** [comment]
I've fixed the current problem by making the `v` prefix optional for the version tags – so no actual action needs to be performed / tags changed / etc. ...

**Comment by CatoTH** [comment]
Hi @macwinnie,
sorry for the confusion!
No that was not intentional, the title of the release was still with with `v` after all. I'll make sure to use the proper names again next time.
