### ISSUE TITLE
Tagesordnungspunkte mit langer Überschrift

### ISSUE THREAD

**Issue by b90g** [CatoTH/antragsgruen#690]
Erstelle  ich genestete Tagesordnungspunkte zB 1.1.1 sind manche TOPs  zb 1.1.2 nicht mehr bearbeitbar wenn die Überschrift lang genug ist. 
Das Stiftsymbol wird nicht angezeigt.

Abhilfe hat Neuladen der Seite gebracht.

Ref: https://chatbegruenung.de/channel/antragsgruen?msg=GZMwBsNPeJubbDfAs

Demo kann gerne zu CET/CEST Bürozeiten durchgeführt werden

**Comment by CatoTH** [comment]
@b90g ich hab das jetzt tatsächlich nicht so einfach nachstellen können, wir können gerne morgen gegen Mittag einmal telefonieren. Schreibst du mir ne Mail mit einem Termin / Konferenzlink?

**Comment by b90g** [comment]
Wollte es gerade via OBS aufzeichen und es ist mir selbst nicht mehr gelungen. Weiß nicht mehr genau was meine Eingabe war, aber auch mit der Eingabe der Supportnehmer*in, war es mir nicht möglich das nach zustellen. Oki.
