### ISSUE TITLE
Migrate from deprecated node-sass to dart-sass

### ISSUE THREAD

**Issue by Rotzbua** [CatoTH/antragsgruen#701]
## Problem

The npm dependency `node-sass` is deprecated:
https://sass-lang.com/blog/libsass-is-deprecated

## Solution

The "new" recommendation is to use `dart-sass`.

## Steps

- [x] Update bootstrap-sass
- [x] Migrate custom sass
- [x] Migrate to dart-sass

See PR #700

**Comment by CatoTH** [comment]
Thank you!
(btw, if you want to add yourself to the AUTHORS list, just create a Pull Request :-) )

**Comment by CatoTH** [comment]
@Rotzbua I'm afraid I might need to revert parts of this MR, namely the bootstrap and Math.div parts. Reason for this is that the compilation of SCSS is not only done by the module referenced in package.json, but also by the PHP-based library scssphp. This enables users to dynamically modify the style of their page using the web-UI, as it re-compiles the SCSS on the fly. Unfortunately, The library does not support `Math.div` yet, https://github.com/scssphp/scssphp/issues/419 . It look like they will only support it in the next major version (v2), as they need to refactor bigger parts of their code (use of modules).

**Comment by Rotzbua** [comment]
Thanks for the info. The dependency on php comes as a bit of a surprise. I will look at it again.

**Comment by CatoTH** [comment]
As the bootstrap files are not likely to change a lot, I would be fine with a workaround on PHP side, rewriting the math.div's by the old-style version.

It just means one needs to be careful not to use more of the new functionality not yet supported by phpscss for now.

**Comment by CatoTH** [comment]
I think this is done by now
