### ISSUE TITLE
Allow setting preferred membership

### ISSUE THREAD

**Issue by svenseeberg** [CatoTH/antragsgruen#706]
There are cases where users want to show a different membership than is currently shown. For example in same cases (German) Grüne Jugend memberships are shown instead of Bündnis 90/Die Grünen memberships. The same happens with memberships in a KPV. There could be 3 approaches for this:
- List all memberships
- Allow users to set their preferred membership
- In all cases (yet) the users wanted to display their Bündnis 90/Die Grünen membership instead of GJ/KPV. That means it could be valid to always prefer 1xxxxxx membership keys (in Germany).

**Comment by CatoTH** [comment]
This is implemented on the Verdigado antragsgruen instance now (*.antragsgruen.de). Both the "prioritize 1xxx" and the "select preferred organisation in the account settings" part.
Not yet on the federal instance, will discuss an update there.
