### ISSUE TITLE
Update RSS reader information

### ISSUE THREAD

**Issue by Rotzbua** [CatoTH/antragsgruen#711]
The RSS reader list seems old. Programs may not work properly anymore on current OS versions or are uncommon dependencies.

Example:

**RSSOwl**
Last release: 2014-01-02
Depends on JRE.
Source: https://sourceforge.net/projects/rssowl/files/rssowl%202/

**Comment by CatoTH** [comment]
I replaced RSS Owl by Thunderbird. The RSS functionality there is somewhat quirky, but at least it seems to be maintained and cross-platform.
