### ISSUE TITLE
Security: upgrade password hash algorithm on login

### ISSUE THREAD

**Issue by Rotzbua** [CatoTH/antragsgruen#719]
## Current status

Currently, when an account is created, the password is hashed and stored. Therefore, the security of the password hashing algorithm is the same as when the account was created.

## Problem

Over time, it may be that the algorithm used at that time has weaknesses, but there would actually be better algorithms.

## Possible solution

One solution is to check at each login whether a password hash algorithm is used that corresponds to the state of the art.

If an outdated password algorithm is detected, the password is automatically processed and stored with the new algorithm.

## Advantage

In this way, the data set is always migrated to the current state of the technology.
This minimizes the attack surface on passwords after a (hopefully not, but possible) data breach.

## Possible implementation

PHP provides a useful function for this purpose:
https://www.php.net/manual/en/function.password-needs-rehash.php

**Comment by CatoTH** [comment]
I can implement that, but wonder: does anything in that regard actually change? It looks to me like it has always been PASSWORD_BCRYPT with a cost factor of 10, and I didn't catch that changing even in PHP 8.2... are the default values actually still good practice?

**Comment by CatoTH** [comment]
Thanks for pointing that out. I'll probably release the next version later this year (after 8.4 came out and I had time to test it), and would implement such an upgrade then.
