### ISSUE TITLE
PDF-Export gibt mehrere Zeilen in einer Zeile aus

### ISSUE THREAD

**Issue by colichri** [CatoTH/antragsgruen#735]
Die Anträge bei der nächsten Mitgliederversammlung möchte ich auch in gedruckter Form als Tischvorlage auslegen. 
### Problembeschreibung
Bei den exportierten PDFs werden nummerierte Zeilen (sowohl ordered als auch unordered lists) teilweise zusammen in eine Zeile gepackt, sodass sich diese überschreiben und der Text unleserlich wird (siehe angehängte Dateien). 
[SÄ1_Satzung.pdf](https://github.com/CatoTH/antragsgruen/files/10247866/SA1_Satzung.pdf)
[TO1_Vorschlag_zur_Tagesordnung.pdf](https://github.com/CatoTH/antragsgruen/files/10247869/TO1_Vorschlag_zur_Tagesordnung.pdf)
### Lösungsansätze
- Das Ändern der Formatvorlage des PDF-Exports löst das Problem leider nicht.

**Comment by CatoTH** [comment]
@colichri Kannst du mir den Link auf die Online-Fassung schicken, falls das auf *.antragsgruen.de gehostet ist? Weil dann könnte ich mir einmal das zugrunde liegende HTML anschauen, das zu diesem Fehler führt.

**Comment by colichri** [comment]
Gerne, ist zu finden unter gjhn.antragsgruen.deVon meinem iPhone gesendetAm 16.12.2022 um 20:10 schrieb Tobias Hößl ***@***.***>:﻿
@colichri Kannst du mir den Link auf die Online-Fassung schicken, falls das auf *.antragsgruen.de gehostet ist? Weil dann könnte ich mir einmal das zugrunde liegende HTML anschauen, das zu diesem Fehler führt.

**Comment by CatoTH** [comment]
@colichri Zwei Punkte: ich hab gesehen, dass die bevorzugte PDF-Generierung nicht auswählbar war. Wenn du jetzt in den Antragstypen das (neu aufgetauchte) PDF-Layout an fünfter Stelle auswählst, sollte der Fehler damit nicht auftauchen.

Den Fehler im aktuell noch ausgewählten PDF-Layout muss ich mir noch etwas mehr in Ruhe ansehen...
