### ISSUE TITLE
Error: Migration failed: m220102_130212_user_groups

### ISSUE THREAD

**Issue by sOUTHX1337** [CatoTH/antragsgruen#752]
bei dem versuch die Antragsgrün Instanz zu aktualisieren, habe ich diesen Fehler beim Datenbank Update bekommen

Error: Migration failed: m220102_130212_user_groups

**Comment by CatoTH** [comment]
@sOUTHX1337 Hast du, vielleicht aus der runtime/logs/app.log, noch irgendeine genauere Information darüber, was genau schief gelaufen ist?

**Comment by sOUTHX1337** [comment]
müsste das sein, oder

2023-01-19 14:10:37 [-][-][-][error][Exception] Exception: Migration failed: m220102_130212_user_groups in /var/www/co1028_1/htdocs/antragsgruen/components/updater/MigrateHelper.php:49
Stack trace:
#0 /var/www/co1028_1/htdocs/antragsgruen/components/updater/updater.php(127): app\components\updater\MigrateHelper::performMigrations()
#1 /var/www/co1028_1/htdocs/antragsgruen/web/update.php(2): require('/var/www/co1028...')
#2 {main}
2023-01-19 14:10:37 [-][-][-][info][application] $_GET = []

$_POST = [
    'perform_migrations' => ''
]

**Comment by sOUTHX1337** [comment]
Update ging von Version 4.9.1 - leider wurden nicht daran gedacht, bei jedem schritt das Datenbank-Update durchzuführen

**Comment by CatoTH** [comment]
Hm leider steht da nicht, wo genau es schief gegangen ist... :/
Siehst du in der Datenbank noch, ob die Tabelle userConsultationScreening angelegt wurde bzw. einen Foreign Key von consultationId auf consultation.id gesetzt hat? Weil wenn ja, müsste man nur noch händisch ein paar Tabelleneinträge ergänzen

**Comment by sOUTHX1337** [comment]
Die Tabelle wurde angelegt, bezüglich Foreign Key hilft der screen weiter? Datenbanken sind nich ganz so meins

![image](https://user-images.githubusercontent.com/16980942/213455239-606d20ea-07bc-4f84-89a6-9266e0e8792a.png)

**Comment by CatoTH** [comment]
Also vorausgesetzt, du hast nur genau einen Eintrag in `site` (das ist fast immer so), und nur eine `consultation`, kann man die Benutzergruppen von Hand so anlegen:
```
INSERT INTO `consultationUserGroup` (`id`, `externalId`, `templateId`, `title`, `consultationId`, `siteId`, `position`, `selectable`, `permissions`) VALUES
(1, NULL, 1, 'Site admin', NULL, 1, 0, 1, 'admin-all'),
(2, NULL, 2, 'Consultation admin', 1, 1, 0, 1, 'admin-all'),
(3, NULL, 3, 'Proposed procedure', 1, 1, 0, 1, 'proposed-procedure'),
(4, NULL, 4, 'Participant', 1, 1, 0, 1, '');
```
Wenn es mehrere Einträge unter Consultation gibt, muss man Zeile 2-4 entsprechend wiederholen leider.

Dann von Hand eintragen, dass die Migration durchgeführt ist:
```
INSERT INTO `migration` (`version`, `apply_time`) VALUES ('m220102_130212_user_groups', 1645948034);
```

Und dann kann man ggf. im Update Tool weitermachen.

Danach werden aber alle gesonderten Benutzerberechtigungen weg sein - nur noch der Super-User, also der, der bei der Ersteinrichtung eingegeben wurde, (id=1 in der User-Tabelle) hat noch Admin-Rechte. In der Benutzerverwaltung kann man das nachtragen.

**Comment by sOUTHX1337** [comment]
`site` haben wir eine, `consultation` insgesamt 7

für den ersten SQL befehlt, hat die Tabelle `position` gefehlt, diese manuell hinzugefügt, dann hat es funktioniert.


Beim weitermachen mit dem Update Tool kommt nun
"Error: Migration failed: m220730_144556_voting_block_settings_usergroup_order"

**Comment by sOUTHX1337** [comment]
scheint alles funktioniert zu haben - vielen dank für die unglaublich schnelle hilfe!
