### ISSUE TITLE
OpenSlides Plugin aktivieren

### ISSUE THREAD

**Issue by sOUTHX1337** [CatoTH/antragsgruen#753]
noch ein punkt von mir - leider finde ich nicht heraus, wie man Plugins aktiviert. konkret ist das OpenSlides Plugin gemeint.

Ich habe das Plugin vom github geladen und in den `plugins ` Ordner verschoben. alles Caches auch geleert

**Comment by CatoTH** [comment]
Plugins muss man in der config.json aktivieren, indem man es z.B. a la ""plugins": ["openslides"]" einträgt.
Ich muss da jetzt aber die Erwartungen dämpfen: das Plugin war wirklich nur für einen ganz speziellen Fall programmiert, wo es darum ging, die Benutzerverwaltung synchron zu halten und fürs Antragsgrün-Login OpenSlides als Backend zu verwenden. Es funktionierte auch nur, wenn der https://github.com/CatoTH/OpenSlides-Proxy Proxy parallel lief und auf die laufende OS- und Antragsgrün-Instanz hin konfiguriert war.
Ich weiß nicht, wofür ihr es einsetzen wollt - aber ich wäre sehr überrascht, wenn das Plugin respektive das Plugin von Haus aus genau das tut, was ihr sucht. Bei solchen Themen sind wir meisten in einem Bereich, wo ich dann auf Auftragsbasis Integrationsdienstleitungen erbringe.

**Comment by sOUTHX1337** [comment]
an die config habe ich gar nicht gedacht - wäre ggf. ein guter punkt zu erweitern auf der hilfe seite.

die benutzerverwaltung synchronisieren wäre für uns praktisch, aber fraglich ob das "pflegen" des proxys das ganz wert ist.
openslides wird bei uns hauptsächlich wegen der prästentation und abstimmung genutzt. also aktuell ist es bei uns viel rumprobieren, was den größten nutzen hat.
