### ISSUE TITLE
Where is the SAML config?

### ISSUE THREAD

**Issue by zner0L** [CatoTH/antragsgruen#786]
I am trying to set up SAML to authorize users with my Keycloak, but I can't find any documentation on it. I can see how it is done in https://github.com/CatoTH/antragsgruen/tree/main/plugins/gruene_de_saml, which should be easy enough to copy and adapt, but I don‘t understand how  `SimpleSAML` gets the SAML config. Shouldn't there be an `authsources.php` somewhere? I would appreciate your help, if you can spare the time. 

Thank you so much for keeping this project open source. It is really helpful!

**Comment by CatoTH** [comment]
The location can be configured by the SIMPLESAMLPHP_CONFIG_DIR environment variable, which can be set e.g. in the nginx configuration: https://github.com/CatoTH/antragsgruen/blob/main/docs/simplesaml-nginx.conf#L28

And yes, there needs to be a authsources.php, a config.php and saml20-idp-remote.php .

Honestly, setting up SAML always was somewhat tricky and somehow different every single time depending on so many factors that I didn't dare to write a authorative documentation yet. For those installations using it against a Keycloak server, I usually did some client-specific implementation (as seen in the plugin-directory. though gruene_ch_saml might be the easier basis to start from)

**Comment by lukas-staab** [comment]
I also want to connect a keycloak to it. Have you started allready / do you have a PR at hand @zner0L ?

**Comment by CatoTH** [comment]
I'm closing this. because apparently you have figured it out (according to https://github.com/CatoTH/antragsgruen/pull/822)
