### ISSUE TITLE
Unclear assert in `DiffRendererTest`

### ISSUE THREAD

**Issue by Rotzbua** [CatoTH/antragsgruen#807]
## Problem

The assertion is not type safe:

https://github.com/CatoTH/antragsgruen/blob/af9a297bbb49197a2b0cc776632219912943cfe3/tests/unit/DiffRendererTest.php#L116

## Description

I changed it in #799 to strict type assertion and it fails with:

```
DiffRendererTest: Split text
 Test  tests/Unit/DiffRendererTest.php:testSplitText
Failed asserting that null is false.
#1  /home/runner/work/antragsgruen/antragsgruen/tests/Unit/DiffRendererTest.php:114
#2  /home/runner/work/antragsgruen/antragsgruen/vendor/bin/codecept:119
```

Is it correct that `null` is returned instead of `false` ?

**Comment by CatoTH** [comment]
Yes, null was correct. I fixed the test.
