### ISSUE TITLE
Upload von User-Fonts

### ISSUE THREAD

**Issue by CatoTH** [CatoTH/antragsgruen#81]
Anforderung von Christian

**Comment by CatoTH** [comment]
Mir fällt gerade keine Möglichkeit ein, das wirklich sinnvoll umzusetzen, da für eine vollumfängliche Schriftartenunterstützung über ein Dutzend Dateien nötig wären (normal, kursiv, fett, kursiv/fett, jeweils als Woff, Svg, ttf usw.)
Stattdessen wird es sinnvoller sein, Layout-Varianten anzufertigen.

**Comment by patrickhanft** [comment]
Support Markdown *muahahaha*

**Comment by CatoTH** [comment]
Kann Markdown inzwischen eingebettete Webfonts? ^^
