### ISSUE TITLE
Fehler bei PDF export von ÄA

### ISSUE THREAD

**Issue by sOUTHX1337** [CatoTH/antragsgruen#811]
Beim Versuch die PDF eines Antrages herunterzuladen erscheint im Web der "Fehler #2" - im log wird folgendes ausgeworfen:

siehe Anhang

Normale Anträge sind davon nicht betroffen

woran könnte es liegen?
[app.log](https://github.com/CatoTH/antragsgruen/files/11673354/app.log)

**Comment by sOUTHX1337** [comment]
Das ganze passiert nur bei der PDF Vorlage "LDK Bayern"

**Comment by CatoTH** [comment]
Das klingt nach einem Problem, wenn Antragsgrün auf einem Shared Hosting System gehostet wird, das den Dateizugriff beschränkt. Siehe z.B. ähnliche Probleme bei Wordpress: https://wordpress.org/support/topic/php-warning-is_file-open_basedir-restriction-in-effect-2/ . Ich befürchte jetzt auf die Schnelle könnte da wenn dann nur der Hoster etwas daran ändern. (Wobei ich auch nicht garantieren kann, dass es dann funktionieren würde)

**Comment by sOUTHX1337** [comment]
Folgende Infos kamen von unserem Hoster:

Es wird versucht, auf den Pfad
> /web/stupa2023/page/files/Logo%2BLandscape.png
zuzugreifen, den es nicht gibt.
Alle eure Dateien liegen unterhalb von
> /var/www/co1028_1/

Ich habe mal gesucht, es gibt auch keinerlei Ordner namens "stupa2023" 
in eurem Webspace und auch keine Datei namens "Logo%2BLandscape.png"

**Comment by CatoTH** [comment]
Dass es die Datei nicht gibt ist normalerweise auch gar nicht schlimm. Es wird explizit überprüft, ob es sie gibt. Nur stürzt beim konkreten Setup leider genau diese Prüfung schon ab, ob es die Datei gibt...

Ich hab hier jetzt mal einen Patch geschrieben, der das abfängt: https://github.com/CatoTH/antragsgruen/pull/812/commits/7a5c4bbfd5a09e8a4cb737cb7604d4edf9dd41bc . Also einfach einmal
try {
catch (\Exception $e) {}
um die file_exists()-Überprüfung herum packen. Das kannst du gerne auch direkt auf deinem System einbauen.

**Comment by sOUTHX1337** [comment]
Der Patch funktioniert!

Vielen Herzlichen Dank!
