### ISSUE TITLE
Änderungsantrag mit unterschiedlichen Änderungen bei HTML und PDF Version

### ISSUE THREAD

**Issue by melegiul** [CatoTH/antragsgruen#831]
Bei einem Änderungsantrag werden unterschiedliche Änderungen in der PDF und der HTML Versionen angezeigt. Im Diff-HTML heißt es zum Beispiel "Von Zeile 4 bis 8 löschen:", obwohl dort laut dem kompletten Änderungsantragstext und dem Diff-PDF keine Zeilen gelöscht werden sollten.

Betroffener Änderungsantrag: https://2023-5-03-kmv-ka-land.antragsgruen.de/2023-9-13-jhv-ka-land/Beitrags-und-Kassenordnung-des-Kreisverbands-Karlsruhe-Land-2771/66745

[A1_Ä2_Beitrags-_und_Kassenordnung_des_Kreisverbands_Karlsru.pdf](https://github.com/CatoTH/antragsgruen/files/12484155/A1_A2_Beitrags-_und_Kassenordnung_des_Kreisverbands_Karlsru.pdf)

![image](https://github.com/CatoTH/antragsgruen/assets/47010475/f3a9c566-8e9e-4d9f-9754-6c0a3bd83ab3)
*Nur die Änderungen*

![image](https://github.com/CatoTH/antragsgruen/assets/47010475/701d6611-ac38-4518-b166-dd864faa6fff)
*Kompletter Antragstext*

**Comment by CatoTH** [comment]
Hallo,
die Funktion "Standard-Anzeige: Kompletten Antragstext anzeigen" bei den Änderungsantrags-Einstellungen wird leider bei den PDFs noch nicht unterstützt. Ich kann das schon einbauen, allerdings wird das jetzt nicht ganz zeitnah gehen leider.

**Comment by melegiul** [comment]
Hey, danke für deine Antwort. Bei dem Ticket geht es eigentlich nicht um "Kompletten Antragstext anzeigen (PDF)", sondern um diesen Textblock von "Nur die Änderungen anzeigen (HTML)" aus dem ersten Screenshots oben. Das `Von Zeile 4 bis 8 löschen:` ist doch falsch, richtig? Laut PDF und Komplett-Ansicht (HTML) werden Zeile 4-8 doch gar nicht entfernt im Änderungsantrag.
```
Von Zeile 4 bis 8 löschen:

Mitgliedsbeitrag

Der Mitgliedsbeitrag beträgt mindestens 1% vom Nettoeinkommen nach Selbsteinschätzung, jedoch mindestens 10,00 Euro im Monat.

Mitglieder der Grünen Jugend, Schüler*innen, Studierende und Leistungsempfänger*innen zahlen einen ermäßigten Beitrag von 4,00 Euro im Monat. 
```
