### ISSUE TITLE
Bessere Verwaltung lokaler Benutzer

### ISSUE THREAD

**Issue by CatoTH** [CatoTH/antragsgruen#90]
AdministratorInnen sollen lokale Accounts (die nur für eine Veranstaltungsreihe gültig sind) wieder löschen und umbenennen können.

**Comment by CatoTH** [comment]
Wird durch https://github.com/CatoTH/antragsgruen/commit/82fcac1e19e8d97deb8d037b50da29df3798136c umgesetzt.

**Comment by sksksksk** [comment]
I was looking for a way do delete a user with my admin account, but could not find any such option. And then I saw this issue, that is supposed to have implemented this function.

Could you point me to the exact location of this functionality?

I use version 3.7.5
