### ISSUE TITLE
v4.14.0 - No Bundled Release File

### ISSUE THREAD

**Issue by errotu** [CatoTH/antragsgruen#930]
Hi, thanks a lot for creating this great piece of software!

I'm currently using an auto-updater script which [checks the Github API for a new release](https://api.github.com/repos/CatoTH/antragsgruen/releases/latest) and then downloads the bundled release file from the assets. I noticed that v4.14.0 does - for the first time as far as I can tell - not provide such a bundled release, but only the source code. Was this on purpose or by accident?

**Comment by CatoTH** [comment]
Hi!
Sorry, my fault. There were some technical issues uploading the files when I created the release, and after that I simply forgot. I caught up on that now, so you should be able to download the distribution files.

**Comment by errotu** [comment]
Worked perfectly, thanks a lot!
