### ISSUE TITLE
Unable to start the Web-Instaler

### ISSUE THREAD

**Issue by LukasJam** [CatoTH/antragsgruen#940]
Hey everyone,

I have a problem with the installation:

When calling via the browser I get the following message from the file /web/index.php:
"Application green is not yet set up. Please create the config/INSTALLING file and open this page again to enter installation mode."

When creating this file or a config.json file in the /config directory, both with empty content, the server (apache2) is no longer able to access the website (Http error 500). 

Does something need to be added to one of the two?

Thanks in advance.

**Comment by CatoTH** [comment]
Hi,
which file did you use to install the application? It does sound a bit like you installed the source version, not the actual distribution (https://github.com/CatoTH/antragsgruen/releases/download/v4.14.0/antragsgruen-4.14.0.tar.bz2 / https://github.com/CatoTH/antragsgruen/releases/download/v4.14.0/antragsgruen-4.14.0.zip would be correct and should have the INSTALLING file exist without having to do anything.
