### ISSUE TITLE
Unterschiede im Menü zwischen Desktop- und Mobilansicht

### ISSUE THREAD

**Issue by FloJuh** [CatoTH/antragsgruen#951]
### Erwartetes Verhalten:

- In der Mobilen-Ansicht sollten die gleichen Unterpunkte unter "Neuigkeiten" sichtbar sein wie in der Desktop-Ansicht (Aktivitäten, E-Mail-Benachrichtigungen, Feeds, Sammelnde Anträge).
- Die Ansicht für neue Anträge, Änderungsanträge und Kommentare sollte auch in der mobilen Ansicht vorhanden sein.
- Die PDFs sollten, wie in der Desktop-Ansicht, klar die Antragstypen (z.B. Bewerbungen, Sachanträge, Dringlichkeitsanträge) anzeigen, statt nur "PDFS: Anträge".

### Aktuelles Verhalten:

In der Desktop-Ansicht gibt es unter dem Punkt "Neuigkeiten" die folgenden Unterpunkte:
- Aktivitäten
- E-Mail-Benachrichtigungen
- Feeds
- Sammelnde Anträge

In der mobilen Ansicht hingegen gibt es nur den Punkt "Neuigkeiten", der direkt auf die Seite "Sammelnde Anträge" leitet. Es fehlen die Unterpunkte für Aktivitäten, E-Mail-Benachrichtigungen, Feeds und Sammelnde Anträge

Zusätzlich fehlen in der mobilen Ansicht neue Anträge, Änderungsanträge und Kommentare vollständig.

Darüber hinaus gibt es ein Problem mit der Darstellung der PDFs in der mobilen Ansicht: Zwar werden die PDFs zum Download angeboten, wie in der Desktop-Ansicht, jedoch steht dort für jeden Antragstyp, mit Ausnahme der Änderungsanträge, lediglich "PDFS: Anträge". Da es verschiedene Antragstypen geben kann, muss man jedes "PDFS: Anträge" anklicken, um herauszufinden, welcher Antragstyp sich dahinter verbirgt.

### Schritte zur Reproduktion:

1. Webseite in der Desktop-Ansicht aufrufen und Menü überprüfen.
2. Webseite in der mobilen Ansicht aufrufen und Menü überprüfen.

**Comment by CatoTH** [comment]
Hi,
ganz 100% identisch macht wegen dem begrenzten Platz glaube ich nicht Sinn - insbesondere die "Neue Anträge, Änderungsanträge, Kommentare" etc.. Dafür gibt es sonst ja auch die "Aktivitäten"-Seite. Aber darüber hinaus hab ich nochmal nachgebessert und die Struktur etwas überarbeitet, sodass es dem regulären Menü mehr entspricht, siehe Screenshot. Hoffe das passt.

<img width="334" alt="Bildschirmfoto 2024-11-03 um 09 32 27" src="https://github.com/user-attachments/assets/c8bad21d-01f4-44bb-8b30-d0a211e84d39">

**Comment by FloJuh** [comment]
Danke dir, das gefällt mir!

Ich nehme an, die Seite "Sammelnde Anträge" wird unter Neuigkeiten dann auch aufgeführt.

Die PDFs hast du jetzt noch nicht angepasst?
