### ISSUE TITLE
Login confirmation code mail not sent

### ISSUE THREAD

**Issue by svenseeberg** [CatoTH/antragsgruen#955]
After entering a username and password and hitting the Login button, an e-mail should be sent to the user with a confirmation code. However, no e-mail arrives. There are no errors in any log file. The GUI says that an e-mail has been sent.

I'm currently running v4.14.2.

Mail notifications are not broken in general, this seems to be problem specifically for the login confirmation mails. Password reset mails, for example, still work.

**Comment by CatoTH** [comment]
Hi! Is this about the Verdigado installation of Antragsgrün? or a different one?

**Comment by svenseeberg** [comment]
> Hi! Is this about the Verdigado installation of Antragsgrün? or a different one?

Yes, this is antragsgruen.de

**Comment by svenseeberg** [comment]
The problem is most likely that the confirmation e-mail has been sent before but the message indicates that the e-mail now. And "before" can be an arbitrarily long period.

**Comment by CatoTH** [comment]
I added a button to resend the confirmation e-mail.
Now, as to when this would go live, I guess that touches kind of the conversation we had earlier - realistically, the next release of Antragsgrün will probably be around December.
