### ISSUE TITLE
Logo zurücksetzen

### ISSUE THREAD

**Issue by hildebrandecon** [CatoTH/antragsgruen#968]
Nachdem man ein eigenes Logo hochgeladen hat, gibt es scheinbar keinen Weg mehr, zurück zum default zu kommen. Wenn man das Logo löscht, ist man nicht wieder im default, sondern es wird das "Fehlende Datei"-Symbol als Logo angezeigt.

**Comment by CatoTH** [comment]
Das wird im nächsten Release behoben. Falls du mir die URL schickst, kann ich das bei deiner konkreten Version schnell beheben.

**Comment by hildebrandecon** [comment]
Ich hab im source code die richtige Größe gefunden und es per Hand ersetzt, aber danke! 

Was auch nicht so super ist: Wenn man ein sehr großes Logo hochlädt, kann es passieren, dass man gar nichts mehr auf der Website machen kann, weil da nur noch das Logo ist.

**Comment by FloJuh** [comment]
> Was auch nicht so super ist: Wenn man ein sehr großes Logo hochlädt, kann es passieren, dass man gar nichts mehr auf der Website machen kann, weil da nur noch das Logo ist.

duplicate of #928
