### ISSUE TITLE
2FA causes redirection to default consultation

### ISSUE THREAD

**Issue by nichu42** [CatoTH/antragsgruen#993]
With 2FA activated, If I click on a direct link to a consultation, Antragsgrün redirects me to the default consultation instead after logging in. If you are not approved for the default consultation, you get an error message and have to open the link again to actually get there.

With 2FA being deactivated, this doesn't happen — you are taken directly to the address you clicked before logging in.

**Comment by CatoTH** [comment]
Hi! Yes i can confirm that bug. I fixed it (https://github.com/CatoTH/antragsgruen/commit/b062924058e5e73294feb494e68d4973d8df21d3), it will be released with the next minor bugfix release (4.15.1, don't have a date yet though).
